# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_game_types.gd')

const AccountCharacter = Types.AccountCharacter
const AccountState = Types.AccountState
const ChatMessage = Types.ChatMessage
const InventoryAccess = Types.InventoryAccess
const InventoryItem = Types.InventoryItem
const ItemDrop = Types.ItemDrop
const Loot = Types.Loot
const Monster = Types.Monster
const Obstacle = Types.Obstacle
const Player = Types.Player
const WorldInfo = Types.WorldInfo


var reducers: GameModuleReducers
var procedures: GameModuleProcedures
var db: GameModuleDb

func _init() -> void:
	set_meta("module_name", "Game")
	name = "GameModule"
	reducers = preload('res://spacetime_bindings/schema/module_game_reducers.gd').new(self)
	procedures = preload('res://spacetime_bindings/schema/module_game_procedures.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_game_db.gd').new(p_local_db)
