# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. name: String [br]
func enter_world(name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('enter_world', [name], [&'String'])

## 0. id: int [br]
func equip_item(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('equip_item', [id], [&'U64'])

## 0. id: int [br]
## 1. cell: int [br]
func move_item(id: int, cell: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_item', [id, cell], [&'U64', &'U8'])

## 0. x: float [br]
## 1. z: float [br]
func move_to(x: float, z: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_to', [x, z], [&'F32', &'F32'])


func perform_attack() -> SpacetimeDBReducerCall:
	return _client.call_reducer('perform_attack', [], [])

## 0. id: int [br]
func pickup_item_drop(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('pickup_item_drop', [id], [&'U64'])

## 0. id: int [br]
func pickup_loot(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('pickup_loot', [id], [&'U64'])

## 0. message: String [br]
func send_chat(message: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('send_chat', [message], [&'String'])

## 0. direction_x: float [br]
## 1. direction_z: float [br]
func set_move_input(direction_x: float, direction_z: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_move_input', [direction_x, direction_z], [&'F32', &'F32'])


func stop_moving() -> SpacetimeDBReducerCall:
	return _client.call_reducer('stop_moving', [], [])

## 0. id: int [br]
## 1. cell: int [br]
func unequip_item(id: int, cell: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('unequip_item', [id, cell], [&'U64', &'U8'])

## 0. id: int [br]
func use_item(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('use_item', [id], [&'U64'])

