# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. request_id: String [br]
## 1. amount_text: String [br]
func admin_grant_progression_xp(request_id: String, amount_text: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('admin_grant_progression_xp', [request_id, amount_text], [&'String', &'String'])

## 0. request_id: String [br]
## 1. target_text: String [br]
func admin_raise_progression_level(request_id: String, target_text: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('admin_raise_progression_level', [request_id, target_text], [&'String', &'String'])

## 0. character_id: PackedByteArray [br]
## 1. stat_code: String [br]
func allocate_stat(character_id: PackedByteArray, stat_code: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('allocate_stat', [character_id, stat_code], [&'__identity__', &'String'])


func clear_combat_target() -> SpacetimeDBReducerCall:
	return _client.call_reducer('clear_combat_target', [], [])

## 0. slot: int [br]
## 1. name: String [br]
func create_character(slot: int, name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('create_character', [slot, name], [&'U8', &'String'])


func enter_selected_character() -> SpacetimeDBReducerCall:
	return _client.call_reducer('enter_selected_character', [], [])

## 0. name: String [br]
func enter_world(name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('enter_world', [name], [&'String'])

## 0. id: int [br]
func equip_item(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('equip_item', [id], [&'U64'])


func leave_world() -> SpacetimeDBReducerCall:
	return _client.call_reducer('leave_world', [], [])

## 0. id: int [br]
## 1. cell: int [br]
func move_item(id: int, cell: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_item', [id, cell], [&'U64', &'U8'])

## 0. x: float [br]
## 1. z: float [br]
func move_to(x: float, z: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_to', [x, z], [&'F32', &'F32'])


func open_account() -> SpacetimeDBReducerCall:
	return _client.call_reducer('open_account', [], [])


func perform_attack() -> SpacetimeDBReducerCall:
	return _client.call_reducer('perform_attack', [], [])

## 0. id: int [br]
func pickup_item_drop(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('pickup_item_drop', [id], [&'U64'])

## 0. id: int [br]
func pickup_loot(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('pickup_loot', [id], [&'U64'])

## 0. request_id: String [br]
## 1. target_account: PackedByteArray [br]
## 2. enabled: bool [br]
## 3. reason: String [br]
func provision_progression_operator(request_id: String, target_account: PackedByteArray, enabled: bool, reason: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('provision_progression_operator', [request_id, target_account, enabled, reason], [&'String', &'__identity__', &'Bool', &'String'])

## 0. request_id: String [br]
func request_command_help(request_id: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('request_command_help', [request_id], [&'String'])

## 0. character_id: PackedByteArray [br]
func select_character(character_id: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('select_character', [character_id], [&'__identity__'])

## 0. target_id: int [br]
## 1. target_life_sequence: int [br]
func select_combat_target(target_id: int, target_life_sequence: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('select_combat_target', [target_id, target_life_sequence], [&'U32', &'U32'])

## 0. message: String [br]
func send_chat(message: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('send_chat', [message], [&'String'])

## 0. direction_x: float [br]
## 1. direction_z: float [br]
func set_move_input(direction_x: float, direction_z: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_move_input', [direction_x, direction_z], [&'F32', &'F32'])


func stop_moving() -> SpacetimeDBReducerCall:
	return _client.call_reducer('stop_moving', [], [])

## 0. id: int [br]
## 1. cell: int [br]
func unequip_item(id: int, cell: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('unequip_item', [id, cell], [&'U64', &'U8'])

## 0. id: int [br]
func use_item(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('use_item', [id], [&'U64'])

