# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Game: GameModuleClient

func _init() -> void:
	Game = preload('res://spacetime_bindings/schema/module_game_client.gd').new()
	add_child(Game)
