#!/usr/bin/env python3
"""Generate pinned GDScript bindings without disturbing the running editor."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "client/spacetime_bindings"
SDK_COMMIT = "f6c59d7068e5dacbde0559906746d0a6c5933ffb"


def run_godot(godot: str, stage: Path, *args: str) -> None:
    environment = os.environ.copy()
    environment["XDG_DATA_HOME"] = str(stage / ".data")
    environment["XDG_CONFIG_HOME"] = str(stage / ".config")
    command = [godot, "--headless", "--path", str(stage), *args]
    result = subprocess.run(
        command,
        env=environment,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=120,
        check=False,
    )
    if result.returncode or "SCRIPT ERROR:" in result.stdout or "\nERROR:" in result.stdout:
        raise RuntimeError(f"Godot binding generation failed:\n{result.stdout}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server", default="http://127.0.0.1:3210")
    parser.add_argument("--database", default="mt2-dev-world")
    parser.add_argument("--godot", default=os.environ.get("GODOT", "godot"))
    parser.add_argument("--offline", action="store_true", help="Use the committed schema snapshot.")
    options = parser.parse_args()
    schema_path = DESTINATION / "schema.json"
    if options.offline:
        schema = json.loads(schema_path.read_text())
    else:
        base = options.server.rstrip("/")
        database = urllib.parse.quote(options.database, safe="")
        url = f"{base}/v1/database/{database}/schema?version=10"
        with urllib.request.urlopen(url, timeout=15) as response:
            schema = json.load(response)
    canonical_schema = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    (ROOT / ".local").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="codegen-", dir=ROOT / ".local") as scratch:
        stage = Path(scratch)
        shutil.copytree(ROOT / "client/addons/SpacetimeDB", stage / "addons/SpacetimeDB")
        shutil.copy2(ROOT / "client/scripts/net/generate_bindings.gd", stage / "generate.gd")
        (stage / "schema.json").write_text(canonical_schema)
        (stage / "project.godot").write_text(
            'config_version=5\n[application]\nconfig/name="MT2 Bindings Generator"\n'
            '[rendering]\nrenderer/rendering_method="gl_compatibility"\n'
        )
        run_godot(options.godot, stage, "--editor", "--import", "--quit")
        run_godot(options.godot, stage, "--script", "res://generate.gd")
        run_godot(options.godot, stage, "--editor", "--import", "--quit")
        generated = stage / "spacetime_bindings/schema"
        if not (generated / "module_game_client.gd").is_file():
            raise RuntimeError("The upstream generator did not produce a game client.")
        # Editor import alone can defer errors in scripts loaded only at login.
        # Instantiate the actual client to validate every generated table type.
        (stage / "validate.gd").write_text(
            "extends SceneTree\nfunc _initialize():\n"
            '\tvar module = load("res://spacetime_bindings/schema/module_game_client.gd")\n'
            "\tif module == null or not module.can_instantiate():\n"
            "\t\tquit(1)\n\t\treturn\n"
            "\tvar client = module.new()\n\tclient.free()\n\tquit()\n"
        )
        run_godot(options.godot, stage, "--script", "res://validate.gd")
        output = DESTINATION / "schema"
        DESTINATION.mkdir(parents=True, exist_ok=True)
        # This directory is exclusively generated; preserve SDK and gameplay source.
        if output.exists():
            shutil.rmtree(output)
        shutil.copytree(generated, output)
        schema_path.write_text(canonical_schema)
        manifest = {
            "sdk_commit": SDK_COMMIT,
            "schema_sha256": hashlib.sha256(canonical_schema.encode()).hexdigest(),
            "files": {
                str(path.relative_to(output)): hashlib.sha256(path.read_bytes()).hexdigest()
                for path in sorted(output.rglob("*.gd"))
            },
        }
        (DESTINATION / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
        (DESTINATION / "README.md").write_text(
            "# Generated SpacetimeDB bindings\n\n"
            "Generated by `python3 tools/generate_bindings.py` using the pinned GDScript SDK.\n"
            "Edit Rust tables and reducers, publish the server, then regenerate these files.\n"
            "Use `--offline` to regenerate from the committed `schema.json` snapshot.\n"
            "The game creates SDK clients through `GameConnection`; no SDK autoload is needed.\n"
        )
    print(
        json.dumps(
            {"generated": len(manifest["files"]), "schema_sha256": manifest["schema_sha256"]}
        )
    )


if __name__ == "__main__":
    main()
