# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameItemRecovery extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var owner: PackedByteArray
@export var life_sequence: int
@export var hp: int
@export var sp: int
@export var next_tick_us: int

#BSATN metadata
const primary_key: StringName = &'owner'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"owner": "__identity__",
	"life_sequence": "U32",
	"hp": "U32",
	"sp": "U32",
	"next_tick_us": "I64"
}

## 1. owner: PackedByteArray[br]
## 2. life_sequence: int[br]
## 3. hp: int[br]
## 4. sp: int[br]
## 5. next_tick_us: int[br]
static func create(p_owner: PackedByteArray, p_life_sequence: int, p_hp: int, p_sp: int, p_next_tick_us: int) -> GameItemRecovery:
	var result: GameItemRecovery = GameItemRecovery.new()
	result.owner = p_owner
	result.life_sequence = p_life_sequence
	result.hp = p_hp
	result.sp = p_sp
	result.next_tick_us = p_next_tick_us
	return result
