# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameInventoryState extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var owner: PackedByteArray
@export var next_potion_us: int

#BSATN metadata
const primary_key: StringName = &'owner'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"owner": "__identity__",
	"next_potion_us": "I64"
}

## 1. owner: PackedByteArray[br]
## 2. next_potion_us: int[br]
static func create(p_owner: PackedByteArray, p_next_potion_us: int) -> GameInventoryState:
	var result: GameInventoryState = GameInventoryState.new()
	result.owner = p_owner
	result.next_potion_us = p_next_potion_us
	return result
