# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameObstacle extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['obstacle']

@export var id: int
@export var x: float
@export var z: float
@export var half_x: float
@export var half_z: float
@export var height: float
@export var kind: String

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"x": "F32",
	"z": "F32",
	"half_x": "F32",
	"half_z": "F32",
	"height": "F32",
	"kind": "String"
}

## 1. id: int[br]
## 2. x: float[br]
## 3. z: float[br]
## 4. half_x: float[br]
## 5. half_z: float[br]
## 6. height: float[br]
## 7. kind: String[br]
static func create(p_id: int, p_x: float, p_z: float, p_half_x: float, p_half_z: float, p_height: float, p_kind: String) -> GameObstacle:
	var result: GameObstacle = GameObstacle.new()
	result.id = p_id
	result.x = p_x
	result.z = p_z
	result.half_x = p_half_x
	result.half_z = p_half_z
	result.height = p_height
	result.kind = p_kind
	return result
