# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCommandFeedback extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['command_feedback']

@export var id: int
@export var account: PackedByteArray
@export var request_id: String
@export var severity: String
@export var message: String
@export var created_at: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"account": "__identity__",
	"request_id": "String",
	"severity": "String",
	"message": "String",
	"created_at": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. account: PackedByteArray[br]
## 3. request_id: String[br]
## 4. severity: String[br]
## 5. message: String[br]
## 6. created_at: int[br]
static func create(p_id: int, p_account: PackedByteArray, p_request_id: String, p_severity: String, p_message: String, p_created_at: int) -> GameCommandFeedback:
	var result: GameCommandFeedback = GameCommandFeedback.new()
	result.id = p_id
	result.account = p_account
	result.request_id = p_request_id
	result.severity = p_severity
	result.message = p_message
	result.created_at = p_created_at
	return result
