# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCombatTargetView extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['combat_target_view']

@export var account: PackedByteArray
@export var character_id: PackedByteArray
@export var target_id: int
@export var target_life_sequence: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"account": "__identity__",
	"character_id": "__identity__",
	"target_id": "U32",
	"target_life_sequence": "U32"
}

## 1. account: PackedByteArray[br]
## 2. character_id: PackedByteArray[br]
## 3. target_id: int[br]
## 4. target_life_sequence: int[br]
static func create(p_account: PackedByteArray, p_character_id: PackedByteArray, p_target_id: int, p_target_life_sequence: int) -> GameCombatTargetView:
	var result: GameCombatTargetView = GameCombatTargetView.new()
	result.account = p_account
	result.character_id = p_character_id
	result.target_id = p_target_id
	result.target_life_sequence = p_target_life_sequence
	return result
