# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterForce extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var monster_id: int
@export var monster_life_sequence: int
@export var source_character: PackedByteArray
@export var source_action_revision: int
@export var started_at_us: int
@export var consumed_elapsed_us: int
@export var direction_x: float
@export var direction_z: float
@export var distance_m: float
@export var duration_us: int

#BSATN metadata
const primary_key: StringName = &'monster_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"monster_life_sequence": "U32",
	"source_character": "__identity__",
	"source_action_revision": "U64",
	"started_at_us": "I64",
	"consumed_elapsed_us": "I64",
	"direction_x": "F32",
	"direction_z": "F32",
	"distance_m": "F64",
	"duration_us": "I64"
}

## 1. monster_id: int[br]
## 2. monster_life_sequence: int[br]
## 3. source_character: PackedByteArray[br]
## 4. source_action_revision: int[br]
## 5. started_at_us: int[br]
## 6. consumed_elapsed_us: int[br]
## 7. direction_x: float[br]
## 8. direction_z: float[br]
## 9. distance_m: float[br]
## 10. duration_us: int[br]
static func create(p_monster_id: int, p_monster_life_sequence: int, p_source_character: PackedByteArray, p_source_action_revision: int, p_started_at_us: int, p_consumed_elapsed_us: int, p_direction_x: float, p_direction_z: float, p_distance_m: float, p_duration_us: int) -> GameMonsterForce:
	var result: GameMonsterForce = GameMonsterForce.new()
	result.monster_id = p_monster_id
	result.monster_life_sequence = p_monster_life_sequence
	result.source_character = p_source_character
	result.source_action_revision = p_source_action_revision
	result.started_at_us = p_started_at_us
	result.consumed_elapsed_us = p_consumed_elapsed_us
	result.direction_x = p_direction_x
	result.direction_z = p_direction_z
	result.distance_m = p_distance_m
	result.duration_us = p_duration_us
	return result
