# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAdminRate extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var account: PackedByteArray
@export var next_progression_us: int
@export var next_help_us: int

#BSATN metadata
const primary_key: StringName = &'account'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"account": "__identity__",
	"next_progression_us": "I64",
	"next_help_us": "I64"
}

## 1. account: PackedByteArray[br]
## 2. next_progression_us: int[br]
## 3. next_help_us: int[br]
static func create(p_account: PackedByteArray, p_next_progression_us: int, p_next_help_us: int) -> GameAdminRate:
	var result: GameAdminRate = GameAdminRate.new()
	result.account = p_account
	result.next_progression_us = p_next_progression_us
	result.next_help_us = p_next_help_us
	return result
