# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCharacterBuff extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: String
@export var character_id: PackedByteArray
@export var skill_vnum: int
@export var life_sequence: int
@export var active_since_us: int
@export var next_tick_us: int
@export var modifiers: Array[GameSavedBuffModifier]

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "String",
	"character_id": "__identity__",
	"skill_vnum": "U16",
	"life_sequence": "U32",
	"active_since_us": "I64",
	"next_tick_us": "I64",
	"modifiers": "vec_GameSavedBuffModifier"
}

## 1. id: String[br]
## 2. character_id: PackedByteArray[br]
## 3. skill_vnum: int[br]
## 4. life_sequence: int[br]
## 5. active_since_us: int[br]
## 6. next_tick_us: int[br]
## 7. modifiers: Array[GameSavedBuffModifier][br]
static func create(p_id: String, p_character_id: PackedByteArray, p_skill_vnum: int, p_life_sequence: int, p_active_since_us: int, p_next_tick_us: int, p_modifiers: Array[GameSavedBuffModifier]) -> GameCharacterBuff:
	var result: GameCharacterBuff = GameCharacterBuff.new()
	result.id = p_id
	result.character_id = p_character_id
	result.skill_vnum = p_skill_vnum
	result.life_sequence = p_life_sequence
	result.active_since_us = p_active_since_us
	result.next_tick_us = p_next_tick_us
	result.modifiers = p_modifiers
	return result
