# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAccountControl extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var account: PackedByteArray
@export var connection_id: PackedByteArray
@export var expires_at_us: int

#BSATN metadata
const primary_key: StringName = &'account'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"account": "__identity__",
	"connection_id": "__connection_id__",
	"expires_at_us": "I64"
}

## 1. account: PackedByteArray[br]
## 2. connection_id: PackedByteArray[br]
## 3. expires_at_us: int[br]
static func create(p_account: PackedByteArray, p_connection_id: PackedByteArray, p_expires_at_us: int) -> GameAccountControl:
	var result: GameAccountControl = GameAccountControl.new()
	result.account = p_account
	result.connection_id = p_connection_id
	result.expires_at_us = p_expires_at_us
	return result
