# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameQuestSelection extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['quest_selection']

@export var character_id: PackedByteArray
@export var account: PackedByteArray
@export var npc_vnum: int
@export var quest_index: int
@export var options: Array[String]
@export var branches_json: String
@export var created_at_us: int
@export var expires_at_us: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"account": "__identity__",
	"npc_vnum": "U32",
	"quest_index": "U16",
	"options": "vec_String",
	"branches_json": "String",
	"created_at_us": "I64",
	"expires_at_us": "I64"
}

## 1. character_id: PackedByteArray[br]
## 2. account: PackedByteArray[br]
## 3. npc_vnum: int[br]
## 4. quest_index: int[br]
## 5. options: Array[String][br]
## 6. branches_json: String[br]
## 7. created_at_us: int[br]
## 8. expires_at_us: int[br]
static func create(p_character_id: PackedByteArray, p_account: PackedByteArray, p_npc_vnum: int, p_quest_index: int, p_options: Array[String], p_branches_json: String, p_created_at_us: int, p_expires_at_us: int) -> GameQuestSelection:
	var result: GameQuestSelection = GameQuestSelection.new()
	result.character_id = p_character_id
	result.account = p_account
	result.npc_vnum = p_npc_vnum
	result.quest_index = p_quest_index
	result.options = p_options
	result.branches_json = p_branches_json
	result.created_at_us = p_created_at_us
	result.expires_at_us = p_expires_at_us
	return result
