# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterStun extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['monster_stun']

@export var monster_id: int
@export var life_sequence: int
@export var starts_at_us: int
@export var expires_at_us: int

#BSATN metadata
const primary_key: StringName = &'monster_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"life_sequence": "U32",
	"starts_at_us": "I64",
	"expires_at_us": "I64"
}

## 1. monster_id: int[br]
## 2. life_sequence: int[br]
## 3. starts_at_us: int[br]
## 4. expires_at_us: int[br]
static func create(p_monster_id: int, p_life_sequence: int, p_starts_at_us: int, p_expires_at_us: int) -> GameMonsterStun:
	var result: GameMonsterStun = GameMonsterStun.new()
	result.monster_id = p_monster_id
	result.life_sequence = p_life_sequence
	result.starts_at_us = p_starts_at_us
	result.expires_at_us = p_expires_at_us
	return result
