# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterThreat extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: String
@export var monster_id: int
@export var monster_life: int
@export var character_id: PackedByteArray
@export var character_life: int
@export var score: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "String",
	"monster_id": "U32",
	"monster_life": "U32",
	"character_id": "__identity__",
	"character_life": "U32",
	"score": "I32"
}

## 1. id: String[br]
## 2. monster_id: int[br]
## 3. monster_life: int[br]
## 4. character_id: PackedByteArray[br]
## 5. character_life: int[br]
## 6. score: int[br]
static func create(p_id: String, p_monster_id: int, p_monster_life: int, p_character_id: PackedByteArray, p_character_life: int, p_score: int) -> GameMonsterThreat:
	var result: GameMonsterThreat = GameMonsterThreat.new()
	result.id = p_id
	result.monster_id = p_monster_id
	result.monster_life = p_monster_life
	result.character_id = p_character_id
	result.character_life = p_character_life
	result.score = p_score
	return result
