# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameNpcSpawn extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['npc_spawn']

@export var spawn_id: String
@export var actor_id: String
@export var map_id: String
@export var x_cm: int
@export var z_cm: int
@export var height_m: float
@export var heading_degrees: int
@export var yaw: float

#BSATN metadata
const primary_key: StringName = &'spawn_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"spawn_id": "String",
	"actor_id": "String",
	"map_id": "String",
	"x_cm": "I32",
	"z_cm": "I32",
	"height_m": "F32",
	"heading_degrees": "U16",
	"yaw": "F32"
}

## 1. spawn_id: String[br]
## 2. actor_id: String[br]
## 3. map_id: String[br]
## 4. x_cm: int[br]
## 5. z_cm: int[br]
## 6. height_m: float[br]
## 7. heading_degrees: int[br]
## 8. yaw: float[br]
static func create(p_spawn_id: String, p_actor_id: String, p_map_id: String, p_x_cm: int, p_z_cm: int, p_height_m: float, p_heading_degrees: int, p_yaw: float) -> GameNpcSpawn:
	var result: GameNpcSpawn = GameNpcSpawn.new()
	result.spawn_id = p_spawn_id
	result.actor_id = p_actor_id
	result.map_id = p_map_id
	result.x_cm = p_x_cm
	result.z_cm = p_z_cm
	result.height_m = p_height_m
	result.heading_degrees = p_heading_degrees
	result.yaw = p_yaw
	return result
