# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSkillAreaVictim extends Resource

const module_name : String = "Game"
const table_names: Array[String] = []

@export var monster_id: int
@export var life_sequence: int
@export var center_x: float
@export var center_y: float
@export var center_z: float

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"life_sequence": "U32",
	"center_x": "F64",
	"center_y": "F64",
	"center_z": "F64"
}

## 1. monster_id: int[br]
## 2. life_sequence: int[br]
## 3. center_x: float[br]
## 4. center_y: float[br]
## 5. center_z: float[br]
static func create(p_monster_id: int, p_life_sequence: int, p_center_x: float, p_center_y: float, p_center_z: float) -> GameSkillAreaVictim:
	var result: GameSkillAreaVictim = GameSkillAreaVictim.new()
	result.monster_id = p_monster_id
	result.life_sequence = p_life_sequence
	result.center_x = p_center_x
	result.center_y = p_center_y
	result.center_z = p_center_z
	return result
