# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSpecialArea extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var character_id: PackedByteArray
@export var owner_life_sequence: int
@export var action_revision: int
@export var action_started_at_us: int
@export var activation_at_us: int
@export var expires_at_us: int
@export var activated_at_tick_us: int
@export var center_x: float
@export var center_y: float
@export var center_z: float
@export var heading: float
@export var damage: int
@export var hit_count: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"owner_life_sequence": "U32",
	"action_revision": "U64",
	"action_started_at_us": "I64",
	"activation_at_us": "I64",
	"expires_at_us": "I64",
	"activated_at_tick_us": "I64",
	"center_x": "F32",
	"center_y": "F32",
	"center_z": "F32",
	"heading": "F32",
	"damage": "U16",
	"hit_count": "U8"
}

## 1. character_id: PackedByteArray[br]
## 2. owner_life_sequence: int[br]
## 3. action_revision: int[br]
## 4. action_started_at_us: int[br]
## 5. activation_at_us: int[br]
## 6. expires_at_us: int[br]
## 7. activated_at_tick_us: int[br]
## 8. center_x: float[br]
## 9. center_y: float[br]
## 10. center_z: float[br]
## 11. heading: float[br]
## 12. damage: int[br]
## 13. hit_count: int[br]
static func create(p_character_id: PackedByteArray, p_owner_life_sequence: int, p_action_revision: int, p_action_started_at_us: int, p_activation_at_us: int, p_expires_at_us: int, p_activated_at_tick_us: int, p_center_x: float, p_center_y: float, p_center_z: float, p_heading: float, p_damage: int, p_hit_count: int) -> GameSpecialArea:
	var result: GameSpecialArea = GameSpecialArea.new()
	result.character_id = p_character_id
	result.owner_life_sequence = p_owner_life_sequence
	result.action_revision = p_action_revision
	result.action_started_at_us = p_action_started_at_us
	result.activation_at_us = p_activation_at_us
	result.expires_at_us = p_expires_at_us
	result.activated_at_tick_us = p_activated_at_tick_us
	result.center_x = p_center_x
	result.center_y = p_center_y
	result.center_z = p_center_z
	result.heading = p_heading
	result.damage = p_damage
	result.hit_count = p_hit_count
	return result
