# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAdminRequestCollision extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var collision_key: String
@export var request_id: String
@export var actor_account: PackedByteArray
@export var audit_id: int

#BSATN metadata
const primary_key: StringName = &'collision_key'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"collision_key": "String",
	"request_id": "String",
	"actor_account": "__identity__",
	"audit_id": "U64"
}

## 1. collision_key: String[br]
## 2. request_id: String[br]
## 3. actor_account: PackedByteArray[br]
## 4. audit_id: int[br]
static func create(p_collision_key: String, p_request_id: String, p_actor_account: PackedByteArray, p_audit_id: int) -> GameAdminRequestCollision:
	var result: GameAdminRequestCollision = GameAdminRequestCollision.new()
	result.collision_key = p_collision_key
	result.request_id = p_request_id
	result.actor_account = p_actor_account
	result.audit_id = p_audit_id
	return result
