# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterDamage extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var monster_id: int
@export var monster_life_sequence: int
@export var character_id: PackedByteArray
@export var controller_connection_id: PackedByteArray
@export var registered_damage: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"monster_id": "U32",
	"monster_life_sequence": "U32",
	"character_id": "__identity__",
	"controller_connection_id": "__connection_id__",
	"registered_damage": "U32"
}

## 1. id: int[br]
## 2. monster_id: int[br]
## 3. monster_life_sequence: int[br]
## 4. character_id: PackedByteArray[br]
## 5. controller_connection_id: PackedByteArray[br]
## 6. registered_damage: int[br]
static func create(p_id: int, p_monster_id: int, p_monster_life_sequence: int, p_character_id: PackedByteArray, p_controller_connection_id: PackedByteArray, p_registered_damage: int) -> GameMonsterDamage:
	var result: GameMonsterDamage = GameMonsterDamage.new()
	result.id = p_id
	result.monster_id = p_monster_id
	result.monster_life_sequence = p_monster_life_sequence
	result.character_id = p_character_id
	result.controller_connection_id = p_controller_connection_id
	result.registered_damage = p_registered_damage
	return result
