# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSkillAreaPlacement extends Resource

const module_name : String = "Game"
const table_names: Array[String] = []

@export var origin_x: float
@export var origin_y: float
@export var origin_z: float
@export var heading: float
@export var activated_at_us: int
@export var victims: Array[GameSkillAreaVictim]

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"origin_x": "F64",
	"origin_y": "F64",
	"origin_z": "F64",
	"heading": "F32",
	"activated_at_us": "I64",
	"victims": "vec_GameSkillAreaVictim"
}

## 1. origin_x: float[br]
## 2. origin_y: float[br]
## 3. origin_z: float[br]
## 4. heading: float[br]
## 5. activated_at_us: int[br]
## 6. victims: Array[GameSkillAreaVictim][br]
static func create(p_origin_x: float, p_origin_y: float, p_origin_z: float, p_heading: float, p_activated_at_us: int, p_victims: Array[GameSkillAreaVictim]) -> GameSkillAreaPlacement:
	var result: GameSkillAreaPlacement = GameSkillAreaPlacement.new()
	result.origin_x = p_origin_x
	result.origin_y = p_origin_y
	result.origin_z = p_origin_z
	result.heading = p_heading
	result.activated_at_us = p_activated_at_us
	result.victims = p_victims
	return result
