# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterOrigin extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var monster_id: int
@export var definition_vnum: int
@export var home_x: float
@export var home_z: float

#BSATN metadata
const primary_key: StringName = &'monster_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"definition_vnum": "U32",
	"home_x": "F32",
	"home_z": "F32"
}

## 1. monster_id: int[br]
## 2. definition_vnum: int[br]
## 3. home_x: float[br]
## 4. home_z: float[br]
static func create(p_monster_id: int, p_definition_vnum: int, p_home_x: float, p_home_z: float) -> GameMonsterOrigin:
	var result: GameMonsterOrigin = GameMonsterOrigin.new()
	result.monster_id = p_monster_id
	result.definition_vnum = p_definition_vnum
	result.home_x = p_home_x
	result.home_z = p_home_z
	return result
