# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterRegeneration extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var next_tick_us: Option
@export var initial: bool
@export var owners: Array[int]
@export var last_owner: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"next_tick_us": "opt_I64",
	"initial": "Bool",
	"owners": "vec_U64",
	"last_owner": "U64"
}

## 1. id: int[br]
## 2. next_tick_us: Option[br]
## 3. initial: bool[br]
## 4. owners: Array[int][br]
## 5. last_owner: int[br]
static func create(p_id: int, p_next_tick_us: Option, p_initial: bool, p_owners: Array[int], p_last_owner: int) -> GameMonsterRegeneration:
	var result: GameMonsterRegeneration = GameMonsterRegeneration.new()
	result.id = p_id
	result.next_tick_us = p_next_tick_us
	result.initial = p_initial
	result.owners = p_owners
	result.last_owner = p_last_owner
	return result
