# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAdminAudit extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var request_id: String
@export var created_at: int
@export var protocol_version: int
@export var definition_hash: String
@export var actor_account: PackedByteArray
@export var target_account: PackedByteArray
@export var target_character: PackedByteArray
@export var connection_id: PackedByteArray
@export var action: String
@export var canonical_argument: String
@export var reason: String
@export var outcome: String
@export var reason_code: String
@export var has_progression: bool
@export var before_level: int
@export var before_experience: int
@export var before_level_step: int
@export var before_unspent_stat_points: int
@export var before_random_hp: int
@export var before_random_sp: int
@export var before_health: int
@export var before_max_health: int
@export var before_current_sp: int
@export var before_max_sp: int
@export var after_level: int
@export var after_experience: int
@export var after_level_step: int
@export var after_unspent_stat_points: int
@export var after_random_hp: int
@export var after_random_sp: int
@export var after_health: int
@export var after_max_health: int
@export var after_current_sp: int
@export var after_max_sp: int
@export var applied_experience: int
@export var level_rolls: Array[GameAdminLevelRoll]
@export var small_potions: int
@export var medium_potions: int
@export var stacked_items: int
@export var inserted_items: int
@export var dropped_items: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"request_id": "String",
	"created_at": "__timestamp_micros_since_unix_epoch__",
	"protocol_version": "U32",
	"definition_hash": "String",
	"actor_account": "__identity__",
	"target_account": "__identity__",
	"target_character": "__identity__",
	"connection_id": "__connection_id__",
	"action": "String",
	"canonical_argument": "String",
	"reason": "String",
	"outcome": "String",
	"reason_code": "String",
	"has_progression": "Bool",
	"before_level": "U8",
	"before_experience": "U32",
	"before_level_step": "U8",
	"before_unspent_stat_points": "U16",
	"before_random_hp": "U32",
	"before_random_sp": "U32",
	"before_health": "U16",
	"before_max_health": "U16",
	"before_current_sp": "U32",
	"before_max_sp": "U32",
	"after_level": "U8",
	"after_experience": "U32",
	"after_level_step": "U8",
	"after_unspent_stat_points": "U16",
	"after_random_hp": "U32",
	"after_random_sp": "U32",
	"after_health": "U16",
	"after_max_health": "U16",
	"after_current_sp": "U32",
	"after_max_sp": "U32",
	"applied_experience": "U64",
	"level_rolls": "vec_GameAdminLevelRoll",
	"small_potions": "U16",
	"medium_potions": "U16",
	"stacked_items": "U16",
	"inserted_items": "U16",
	"dropped_items": "U16"
}

## 1. id: int[br]
## 2. request_id: String[br]
## 3. created_at: int[br]
## 4. protocol_version: int[br]
## 5. definition_hash: String[br]
## 6. actor_account: PackedByteArray[br]
## 7. target_account: PackedByteArray[br]
## 8. target_character: PackedByteArray[br]
## 9. connection_id: PackedByteArray[br]
## 10. action: String[br]
## 11. canonical_argument: String[br]
## 12. reason: String[br]
## 13. outcome: String[br]
## 14. reason_code: String[br]
## 15. has_progression: bool[br]
## 16. before_level: int[br]
## 17. before_experience: int[br]
## 18. before_level_step: int[br]
## 19. before_unspent_stat_points: int[br]
## 20. before_random_hp: int[br]
## 21. before_random_sp: int[br]
## 22. before_health: int[br]
## 23. before_max_health: int[br]
## 24. before_current_sp: int[br]
## 25. before_max_sp: int[br]
## 26. after_level: int[br]
## 27. after_experience: int[br]
## 28. after_level_step: int[br]
## 29. after_unspent_stat_points: int[br]
## 30. after_random_hp: int[br]
## 31. after_random_sp: int[br]
## 32. after_health: int[br]
## 33. after_max_health: int[br]
## 34. after_current_sp: int[br]
## 35. after_max_sp: int[br]
## 36. applied_experience: int[br]
## 37. level_rolls: Array[GameAdminLevelRoll][br]
## 38. small_potions: int[br]
## 39. medium_potions: int[br]
## 40. stacked_items: int[br]
## 41. inserted_items: int[br]
## 42. dropped_items: int[br]
static func create(p_id: int, p_request_id: String, p_created_at: int, p_protocol_version: int, p_definition_hash: String, p_actor_account: PackedByteArray, p_target_account: PackedByteArray, p_target_character: PackedByteArray, p_connection_id: PackedByteArray, p_action: String, p_canonical_argument: String, p_reason: String, p_outcome: String, p_reason_code: String, p_has_progression: bool, p_before_level: int, p_before_experience: int, p_before_level_step: int, p_before_unspent_stat_points: int, p_before_random_hp: int, p_before_random_sp: int, p_before_health: int, p_before_max_health: int, p_before_current_sp: int, p_before_max_sp: int, p_after_level: int, p_after_experience: int, p_after_level_step: int, p_after_unspent_stat_points: int, p_after_random_hp: int, p_after_random_sp: int, p_after_health: int, p_after_max_health: int, p_after_current_sp: int, p_after_max_sp: int, p_applied_experience: int, p_level_rolls: Array[GameAdminLevelRoll], p_small_potions: int, p_medium_potions: int, p_stacked_items: int, p_inserted_items: int, p_dropped_items: int) -> GameAdminAudit:
	var result: GameAdminAudit = GameAdminAudit.new()
	result.id = p_id
	result.request_id = p_request_id
	result.created_at = p_created_at
	result.protocol_version = p_protocol_version
	result.definition_hash = p_definition_hash
	result.actor_account = p_actor_account
	result.target_account = p_target_account
	result.target_character = p_target_character
	result.connection_id = p_connection_id
	result.action = p_action
	result.canonical_argument = p_canonical_argument
	result.reason = p_reason
	result.outcome = p_outcome
	result.reason_code = p_reason_code
	result.has_progression = p_has_progression
	result.before_level = p_before_level
	result.before_experience = p_before_experience
	result.before_level_step = p_before_level_step
	result.before_unspent_stat_points = p_before_unspent_stat_points
	result.before_random_hp = p_before_random_hp
	result.before_random_sp = p_before_random_sp
	result.before_health = p_before_health
	result.before_max_health = p_before_max_health
	result.before_current_sp = p_before_current_sp
	result.before_max_sp = p_before_max_sp
	result.after_level = p_after_level
	result.after_experience = p_after_experience
	result.after_level_step = p_after_level_step
	result.after_unspent_stat_points = p_after_unspent_stat_points
	result.after_random_hp = p_after_random_hp
	result.after_random_sp = p_after_random_sp
	result.after_health = p_after_health
	result.after_max_health = p_after_max_health
	result.after_current_sp = p_after_current_sp
	result.after_max_sp = p_after_max_sp
	result.applied_experience = p_applied_experience
	result.level_rolls = p_level_rolls
	result.small_potions = p_small_potions
	result.medium_potions = p_medium_potions
	result.stacked_items = p_stacked_items
	result.inserted_items = p_inserted_items
	result.dropped_items = p_dropped_items
	return result
