# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameInventoryAccess extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['inventory_access']

@export var character_id: PackedByteArray
@export var account: PackedByteArray

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"account": "__identity__"
}

## 1. character_id: PackedByteArray[br]
## 2. account: PackedByteArray[br]
static func create(p_character_id: PackedByteArray, p_account: PackedByteArray) -> GameInventoryAccess:
	var result: GameInventoryAccess = GameInventoryAccess.new()
	result.character_id = p_character_id
	result.account = p_account
	return result
