# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCharacterProgression extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['character_progression']

@export var character_id: PackedByteArray
@export var account: PackedByteArray
@export var level: int
@export var experience: int
@export var next_exp: int
@export var level_step: int
@export var unspent_stat_points: int
@export var strength: int
@export var vitality: int
@export var dexterity: int
@export var intelligence: int
@export var random_hp: int
@export var random_sp: int
@export var current_sp: int
@export var max_sp: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"account": "__identity__",
	"level": "U8",
	"experience": "U32",
	"next_exp": "U32",
	"level_step": "U8",
	"unspent_stat_points": "U16",
	"strength": "U8",
	"vitality": "U8",
	"dexterity": "U8",
	"intelligence": "U8",
	"random_hp": "U32",
	"random_sp": "U32",
	"current_sp": "U32",
	"max_sp": "U32"
}

## 1. character_id: PackedByteArray[br]
## 2. account: PackedByteArray[br]
## 3. level: int[br]
## 4. experience: int[br]
## 5. next_exp: int[br]
## 6. level_step: int[br]
## 7. unspent_stat_points: int[br]
## 8. strength: int[br]
## 9. vitality: int[br]
## 10. dexterity: int[br]
## 11. intelligence: int[br]
## 12. random_hp: int[br]
## 13. random_sp: int[br]
## 14. current_sp: int[br]
## 15. max_sp: int[br]
static func create(p_character_id: PackedByteArray, p_account: PackedByteArray, p_level: int, p_experience: int, p_next_exp: int, p_level_step: int, p_unspent_stat_points: int, p_strength: int, p_vitality: int, p_dexterity: int, p_intelligence: int, p_random_hp: int, p_random_sp: int, p_current_sp: int, p_max_sp: int) -> GameCharacterProgression:
	var result: GameCharacterProgression = GameCharacterProgression.new()
	result.character_id = p_character_id
	result.account = p_account
	result.level = p_level
	result.experience = p_experience
	result.next_exp = p_next_exp
	result.level_step = p_level_step
	result.unspent_stat_points = p_unspent_stat_points
	result.strength = p_strength
	result.vitality = p_vitality
	result.dexterity = p_dexterity
	result.intelligence = p_intelligence
	result.random_hp = p_random_hp
	result.random_sp = p_random_sp
	result.current_sp = p_current_sp
	result.max_sp = p_max_sp
	return result
