# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameQuestObjective extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['quest_objective']

@export var id: int
@export var character_id: PackedByteArray
@export var account: PackedByteArray
@export var quest_index: int
@export var quest_id: String
@export var letter_title: String
@export var label: String
@export var target_vnum: int
@export var amount: int
@export var total: int
@export var remaining_display: bool
@export var updated_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"character_id": "__identity__",
	"account": "__identity__",
	"quest_index": "U16",
	"quest_id": "String",
	"letter_title": "String",
	"label": "String",
	"target_vnum": "U32",
	"amount": "U32",
	"total": "U32",
	"remaining_display": "Bool",
	"updated_at_us": "I64"
}

## 1. id: int[br]
## 2. character_id: PackedByteArray[br]
## 3. account: PackedByteArray[br]
## 4. quest_index: int[br]
## 5. quest_id: String[br]
## 6. letter_title: String[br]
## 7. label: String[br]
## 8. target_vnum: int[br]
## 9. amount: int[br]
## 10. total: int[br]
## 11. remaining_display: bool[br]
## 12. updated_at_us: int[br]
static func create(p_id: int, p_character_id: PackedByteArray, p_account: PackedByteArray, p_quest_index: int, p_quest_id: String, p_letter_title: String, p_label: String, p_target_vnum: int, p_amount: int, p_total: int, p_remaining_display: bool, p_updated_at_us: int) -> GameQuestObjective:
	var result: GameQuestObjective = GameQuestObjective.new()
	result.id = p_id
	result.character_id = p_character_id
	result.account = p_account
	result.quest_index = p_quest_index
	result.quest_id = p_quest_id
	result.letter_title = p_letter_title
	result.label = p_label
	result.target_vnum = p_target_vnum
	result.amount = p_amount
	result.total = p_total
	result.remaining_display = p_remaining_display
	result.updated_at_us = p_updated_at_us
	return result
