# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameInventoryState extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var owner: PackedByteArray

#BSATN metadata
const primary_key: StringName = &'owner'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"owner": "__identity__"
}

## 1. owner: PackedByteArray[br]
static func create(p_owner: PackedByteArray) -> GameInventoryState:
	var result: GameInventoryState = GameInventoryState.new()
	result.owner = p_owner
	return result
