# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameItemDrop extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['item_drop']

@export var id: int
@export var x: float
@export var y: float
@export var z: float
@export var vnum: int
@export var count: int
@export var owner: PackedByteArray
@export var reserved_until_us: int
@export var expires_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"x": "F32",
	"y": "F32",
	"z": "F32",
	"vnum": "U32",
	"count": "U16",
	"owner": "__identity__",
	"reserved_until_us": "I64",
	"expires_at_us": "I64"
}

## 1. id: int[br]
## 2. x: float[br]
## 3. y: float[br]
## 4. z: float[br]
## 5. vnum: int[br]
## 6. count: int[br]
## 7. owner: PackedByteArray[br]
## 8. reserved_until_us: int[br]
## 9. expires_at_us: int[br]
static func create(p_id: int, p_x: float, p_y: float, p_z: float, p_vnum: int, p_count: int, p_owner: PackedByteArray, p_reserved_until_us: int, p_expires_at_us: int) -> GameItemDrop:
	var result: GameItemDrop = GameItemDrop.new()
	result.id = p_id
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.vnum = p_vnum
	result.count = p_count
	result.owner = p_owner
	result.reserved_until_us = p_reserved_until_us
	result.expires_at_us = p_expires_at_us
	return result
