# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameWorldInfo extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['world_info']

@export var id: int
@export var protocol_version: int
@export var map_name: String
@export var map_id: String
@export var content_hash: String
@export var tick_ms: int
@export var half_size: float

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U8",
	"protocol_version": "U32",
	"map_name": "String",
	"map_id": "String",
	"content_hash": "String",
	"tick_ms": "U32",
	"half_size": "F32"
}

## 1. id: int[br]
## 2. protocol_version: int[br]
## 3. map_name: String[br]
## 4. map_id: String[br]
## 5. content_hash: String[br]
## 6. tick_ms: int[br]
## 7. half_size: float[br]
static func create(p_id: int, p_protocol_version: int, p_map_name: String, p_map_id: String, p_content_hash: String, p_tick_ms: int, p_half_size: float) -> GameWorldInfo:
	var result: GameWorldInfo = GameWorldInfo.new()
	result.id = p_id
	result.protocol_version = p_protocol_version
	result.map_name = p_map_name
	result.map_id = p_map_id
	result.content_hash = p_content_hash
	result.tick_ms = p_tick_ms
	result.half_size = p_half_size
	return result
