# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAccountState extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['account_state']

@export var account: PackedByteArray
@export var selected_character: PackedByteArray
@export var in_world: bool

#BSATN metadata
const primary_key: StringName = &'account'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"account": "__identity__",
	"selected_character": "__identity__",
	"in_world": "Bool"
}

## 1. account: PackedByteArray[br]
## 2. selected_character: PackedByteArray[br]
## 3. in_world: bool[br]
static func create(p_account: PackedByteArray, p_selected_character: PackedByteArray, p_in_world: bool) -> GameAccountState:
	var result: GameAccountState = GameAccountState.new()
	result.account = p_account
	result.selected_character = p_selected_character
	result.in_world = p_in_world
	return result
