# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSimulationClock extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['simulation_clock']

@export var id: int
@export var last_tick: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U8",
	"last_tick": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. last_tick: int[br]
static func create(p_id: int, p_last_tick: int) -> GameSimulationClock:
	var result: GameSimulationClock = GameSimulationClock.new()
	result.id = p_id
	result.last_tick = p_last_tick
	return result
