# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAccountCharacter extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['account_character']

@export var character_id: PackedByteArray
@export var account: PackedByteArray
@export var slot: int
@export var name: String
@export var empire: int
@export var character_class: int
@export var sex: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"account": "__identity__",
	"slot": "U8",
	"name": "String",
	"empire": "U8",
	"character_class": "U8",
	"sex": "U8"
}

## 1. character_id: PackedByteArray[br]
## 2. account: PackedByteArray[br]
## 3. slot: int[br]
## 4. name: String[br]
## 5. empire: int[br]
## 6. character_class: int[br]
## 7. sex: int[br]
static func create(p_character_id: PackedByteArray, p_account: PackedByteArray, p_slot: int, p_name: String, p_empire: int, p_character_class: int, p_sex: int) -> GameAccountCharacter:
	var result: GameAccountCharacter = GameAccountCharacter.new()
	result.character_id = p_character_id
	result.account = p_account
	result.slot = p_slot
	result.name = p_name
	result.empire = p_empire
	result.character_class = p_character_class
	result.sex = p_sex
	return result
