# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterClock extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var next_attack_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"next_attack_us": "I64"
}

## 1. id: int[br]
## 2. next_attack_us: int[br]
static func create(p_id: int, p_next_attack_us: int) -> GameMonsterClock:
	var result: GameMonsterClock = GameMonsterClock.new()
	result.id = p_id
	result.next_attack_us = p_next_attack_us
	return result
