# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSavedBuffModifier extends Resource

const module_name : String = "Game"
const table_names: Array[String] = []

@export var point: int
@export var value: int
@export var remaining_ticks: int

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"point": "U8",
	"value": "I32",
	"remaining_ticks": "U32"
}

## 1. point: int[br]
## 2. value: int[br]
## 3. remaining_ticks: int[br]
static func create(p_point: int, p_value: int, p_remaining_ticks: int) -> GameSavedBuffModifier:
	var result: GameSavedBuffModifier = GameSavedBuffModifier.new()
	result.point = p_point
	result.value = p_value
	result.remaining_ticks = p_remaining_ticks
	return result
