# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameItemAudit extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var item_id: int
@export var drop_id: int
@export var owner: PackedByteArray
@export var account: PackedByteArray
@export var vnum: int
@export var previous_count: int
@export var count: int
@export var revision: int
@export var cause: String
@export var created_at: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"item_id": "U64",
	"drop_id": "U64",
	"owner": "__identity__",
	"account": "__identity__",
	"vnum": "U32",
	"previous_count": "U16",
	"count": "U16",
	"revision": "U32",
	"cause": "String",
	"created_at": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. item_id: int[br]
## 3. drop_id: int[br]
## 4. owner: PackedByteArray[br]
## 5. account: PackedByteArray[br]
## 6. vnum: int[br]
## 7. previous_count: int[br]
## 8. count: int[br]
## 9. revision: int[br]
## 10. cause: String[br]
## 11. created_at: int[br]
static func create(p_id: int, p_item_id: int, p_drop_id: int, p_owner: PackedByteArray, p_account: PackedByteArray, p_vnum: int, p_previous_count: int, p_count: int, p_revision: int, p_cause: String, p_created_at: int) -> GameItemAudit:
	var result: GameItemAudit = GameItemAudit.new()
	result.id = p_id
	result.item_id = p_item_id
	result.drop_id = p_drop_id
	result.owner = p_owner
	result.account = p_account
	result.vnum = p_vnum
	result.previous_count = p_previous_count
	result.count = p_count
	result.revision = p_revision
	result.cause = p_cause
	result.created_at = p_created_at
	return result
