# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GamePlayerAppearance extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['player_appearance']

@export var character_id: PackedByteArray
@export var empire: int
@export var character_class: int
@export var sex: int
@export var weapon_vnum: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"empire": "U8",
	"character_class": "U8",
	"sex": "U8",
	"weapon_vnum": "U32"
}

## 1. character_id: PackedByteArray[br]
## 2. empire: int[br]
## 3. character_class: int[br]
## 4. sex: int[br]
## 5. weapon_vnum: int[br]
static func create(p_character_id: PackedByteArray, p_empire: int, p_character_class: int, p_sex: int, p_weapon_vnum: int) -> GamePlayerAppearance:
	var result: GamePlayerAppearance = GamePlayerAppearance.new()
	result.character_id = p_character_id
	result.empire = p_empire
	result.character_class = p_character_class
	result.sex = p_sex
	result.weapon_vnum = p_weapon_vnum
	return result
