# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameChatMessage extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['chat_message']

@export var id: int
@export var sender: PackedByteArray
@export var name: String
@export var message: String
@export var sent_at: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"sender": "__identity__",
	"name": "String",
	"message": "String",
	"sent_at": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. sender: PackedByteArray[br]
## 3. name: String[br]
## 4. message: String[br]
## 5. sent_at: int[br]
static func create(p_id: int, p_sender: PackedByteArray, p_name: String, p_message: String, p_sent_at: int) -> GameChatMessage:
	var result: GameChatMessage = GameChatMessage.new()
	result.id = p_id
	result.sender = p_sender
	result.name = p_name
	result.message = p_message
	result.sent_at = p_sent_at
	return result
