# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonster extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['monster']

@export var id: int
@export var x: float
@export var y: float
@export var z: float
@export var heading: float
@export var health: int
@export var max_health: int
@export var activity: int
@export var attack_sequence: int
@export var respawn_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"x": "F32",
	"y": "F32",
	"z": "F32",
	"heading": "F32",
	"health": "U16",
	"max_health": "U16",
	"activity": "U8",
	"attack_sequence": "U32",
	"respawn_at_us": "I64"
}

## 1. id: int[br]
## 2. x: float[br]
## 3. y: float[br]
## 4. z: float[br]
## 5. heading: float[br]
## 6. health: int[br]
## 7. max_health: int[br]
## 8. activity: int[br]
## 9. attack_sequence: int[br]
## 10. respawn_at_us: int[br]
static func create(p_id: int, p_x: float, p_y: float, p_z: float, p_heading: float, p_health: int, p_max_health: int, p_activity: int, p_attack_sequence: int, p_respawn_at_us: int) -> GameMonster:
	var result: GameMonster = GameMonster.new()
	result.id = p_id
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.heading = p_heading
	result.health = p_health
	result.max_health = p_max_health
	result.activity = p_activity
	result.attack_sequence = p_attack_sequence
	result.respawn_at_us = p_respawn_at_us
	return result
