# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameActiveCharge extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var character_id: PackedByteArray
@export var connection_id: PackedByteArray
@export var source_life: int
@export var skill_vnum: int
@export var rank: int
@export var starts_at_us: int
@export var expires_at_us: int
@export var speed_bonus: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"connection_id": "__connection_id__",
	"source_life": "U32",
	"skill_vnum": "U16",
	"rank": "U8",
	"starts_at_us": "I64",
	"expires_at_us": "I64",
	"speed_bonus": "I32"
}

## 1. character_id: PackedByteArray[br]
## 2. connection_id: PackedByteArray[br]
## 3. source_life: int[br]
## 4. skill_vnum: int[br]
## 5. rank: int[br]
## 6. starts_at_us: int[br]
## 7. expires_at_us: int[br]
## 8. speed_bonus: int[br]
static func create(p_character_id: PackedByteArray, p_connection_id: PackedByteArray, p_source_life: int, p_skill_vnum: int, p_rank: int, p_starts_at_us: int, p_expires_at_us: int, p_speed_bonus: int) -> GameActiveCharge:
	var result: GameActiveCharge = GameActiveCharge.new()
	result.character_id = p_character_id
	result.connection_id = p_connection_id
	result.source_life = p_source_life
	result.skill_vnum = p_skill_vnum
	result.rank = p_rank
	result.starts_at_us = p_starts_at_us
	result.expires_at_us = p_expires_at_us
	result.speed_bonus = p_speed_bonus
	return result
