# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameQuestState extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['quest_state']

@export var id: int
@export var character_id: PackedByteArray
@export var account: PackedByteArray
@export var quest_index: int
@export var quest_id: String
@export var title: String
@export var state: String
@export var sequence: int
@export var started_at_us: int
@export var updated_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"character_id": "__identity__",
	"account": "__identity__",
	"quest_index": "U16",
	"quest_id": "String",
	"title": "String",
	"state": "String",
	"sequence": "U32",
	"started_at_us": "I64",
	"updated_at_us": "I64"
}

## 1. id: int[br]
## 2. character_id: PackedByteArray[br]
## 3. account: PackedByteArray[br]
## 4. quest_index: int[br]
## 5. quest_id: String[br]
## 6. title: String[br]
## 7. state: String[br]
## 8. sequence: int[br]
## 9. started_at_us: int[br]
## 10. updated_at_us: int[br]
static func create(p_id: int, p_character_id: PackedByteArray, p_account: PackedByteArray, p_quest_index: int, p_quest_id: String, p_title: String, p_state: String, p_sequence: int, p_started_at_us: int, p_updated_at_us: int) -> GameQuestState:
	var result: GameQuestState = GameQuestState.new()
	result.id = p_id
	result.character_id = p_character_id
	result.account = p_account
	result.quest_index = p_quest_index
	result.quest_id = p_quest_id
	result.title = p_title
	result.state = p_state
	result.sequence = p_sequence
	result.started_at_us = p_started_at_us
	result.updated_at_us = p_updated_at_us
	return result
