# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameTickSchedule extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var scheduled_id: int
@export var scheduled_at: int

#BSATN metadata
const primary_key: StringName = &'scheduled_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"scheduled_id": "U64",
	"scheduled_at": "scheduled_at"
}

## 1. scheduled_id: int[br]
## 2. scheduled_at: int[br]
static func create(p_scheduled_id: int, p_scheduled_at: int) -> GameTickSchedule:
	var result: GameTickSchedule = GameTickSchedule.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	return result
