# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterReaction extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var monster_id: int
@export var monster_life_sequence: int
@export var phase: int
@export var phase_started_at_us: int
@export var phase_ends_at_us: int
@export var completed_at_tick_us: int

#BSATN metadata
const primary_key: StringName = &'monster_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"monster_life_sequence": "U32",
	"phase": "U8",
	"phase_started_at_us": "I64",
	"phase_ends_at_us": "I64",
	"completed_at_tick_us": "I64"
}

## 1. monster_id: int[br]
## 2. monster_life_sequence: int[br]
## 3. phase: int[br]
## 4. phase_started_at_us: int[br]
## 5. phase_ends_at_us: int[br]
## 6. completed_at_tick_us: int[br]
static func create(p_monster_id: int, p_monster_life_sequence: int, p_phase: int, p_phase_started_at_us: int, p_phase_ends_at_us: int, p_completed_at_tick_us: int) -> GameMonsterReaction:
	var result: GameMonsterReaction = GameMonsterReaction.new()
	result.monster_id = p_monster_id
	result.monster_life_sequence = p_monster_life_sequence
	result.phase = p_phase
	result.phase_started_at_us = p_phase_started_at_us
	result.phase_ends_at_us = p_phase_ends_at_us
	result.completed_at_tick_us = p_completed_at_tick_us
	return result
