# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSpecialAreaVictim extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var character_id: PackedByteArray
@export var action_revision: int
@export var monster_id: int
@export var monster_life_sequence: int
@export var previous_center_x: float
@export var previous_center_y: float
@export var previous_center_z: float
@export var hit: bool

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"character_id": "__identity__",
	"action_revision": "U64",
	"monster_id": "U32",
	"monster_life_sequence": "U32",
	"previous_center_x": "F32",
	"previous_center_y": "F32",
	"previous_center_z": "F32",
	"hit": "Bool"
}

## 1. id: int[br]
## 2. character_id: PackedByteArray[br]
## 3. action_revision: int[br]
## 4. monster_id: int[br]
## 5. monster_life_sequence: int[br]
## 6. previous_center_x: float[br]
## 7. previous_center_y: float[br]
## 8. previous_center_z: float[br]
## 9. hit: bool[br]
static func create(p_id: int, p_character_id: PackedByteArray, p_action_revision: int, p_monster_id: int, p_monster_life_sequence: int, p_previous_center_x: float, p_previous_center_y: float, p_previous_center_z: float, p_hit: bool) -> GameSpecialAreaVictim:
	var result: GameSpecialAreaVictim = GameSpecialAreaVictim.new()
	result.id = p_id
	result.character_id = p_character_id
	result.action_revision = p_action_revision
	result.monster_id = p_monster_id
	result.monster_life_sequence = p_monster_life_sequence
	result.previous_center_x = p_previous_center_x
	result.previous_center_y = p_previous_center_y
	result.previous_center_z = p_previous_center_z
	result.hit = p_hit
	return result
