# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameChargeStatus extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['charge_status']

@export var character_id: PackedByteArray
@export var skill_vnum: int
@export var starts_at_us: int
@export var expires_at_us: int
@export var speed_bonus: int

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"skill_vnum": "U16",
	"starts_at_us": "I64",
	"expires_at_us": "I64",
	"speed_bonus": "I32"
}

## 1. character_id: PackedByteArray[br]
## 2. skill_vnum: int[br]
## 3. starts_at_us: int[br]
## 4. expires_at_us: int[br]
## 5. speed_bonus: int[br]
static func create(p_character_id: PackedByteArray, p_skill_vnum: int, p_starts_at_us: int, p_expires_at_us: int, p_speed_bonus: int) -> GameChargeStatus:
	var result: GameChargeStatus = GameChargeStatus.new()
	result.character_id = p_character_id
	result.skill_vnum = p_skill_vnum
	result.starts_at_us = p_starts_at_us
	result.expires_at_us = p_expires_at_us
	result.speed_bonus = p_speed_bonus
	return result
