# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameNpcSpawnRetry extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var spawn_id: String
@export var next_attempt_us: int

#BSATN metadata
const primary_key: StringName = &'spawn_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"spawn_id": "String",
	"next_attempt_us": "I64"
}

## 1. spawn_id: String[br]
## 2. next_attempt_us: int[br]
static func create(p_spawn_id: String, p_next_attempt_us: int) -> GameNpcSpawnRetry:
	var result: GameNpcSpawnRetry = GameNpcSpawnRetry.new()
	result.spawn_id = p_spawn_id
	result.next_attempt_us = p_next_attempt_us
	return result
