# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAdminLevelRoll extends Resource

const module_name : String = "Game"
const table_names: Array[String] = []

@export var resulting_level: int
@export var hp: int
@export var sp: int

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"resulting_level": "U8",
	"hp": "U32",
	"sp": "U32"
}

## 1. resulting_level: int[br]
## 2. hp: int[br]
## 3. sp: int[br]
static func create(p_resulting_level: int, p_hp: int, p_sp: int) -> GameAdminLevelRoll:
	var result: GameAdminLevelRoll = GameAdminLevelRoll.new()
	result.resulting_level = p_resulting_level
	result.hp = p_hp
	result.sp = p_sp
	return result
