# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCharacterSkill extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['character_skill']

@export var id: String
@export var account: PackedByteArray
@export var character_id: PackedByteArray
@export var skill_vnum: int
@export var rank: int
@export var points_spent: int
@export var revision: int
@export var ready_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "String",
	"account": "__identity__",
	"character_id": "__identity__",
	"skill_vnum": "U16",
	"rank": "U8",
	"points_spent": "U8",
	"revision": "U32",
	"ready_at_us": "I64"
}

## 1. id: String[br]
## 2. account: PackedByteArray[br]
## 3. character_id: PackedByteArray[br]
## 4. skill_vnum: int[br]
## 5. rank: int[br]
## 6. points_spent: int[br]
## 7. revision: int[br]
## 8. ready_at_us: int[br]
static func create(p_id: String, p_account: PackedByteArray, p_character_id: PackedByteArray, p_skill_vnum: int, p_rank: int, p_points_spent: int, p_revision: int, p_ready_at_us: int) -> GameCharacterSkill:
	var result: GameCharacterSkill = GameCharacterSkill.new()
	result.id = p_id
	result.account = p_account
	result.character_id = p_character_id
	result.skill_vnum = p_skill_vnum
	result.rank = p_rank
	result.points_spent = p_points_spent
	result.revision = p_revision
	result.ready_at_us = p_ready_at_us
	return result
