# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameBuffStatus extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['buff_status']

@export var id: String
@export var account: PackedByteArray
@export var character_id: PackedByteArray
@export var skill_vnum: int
@export var life_sequence: int
@export var remaining_ticks: int
@export var paused: bool

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "String",
	"account": "__identity__",
	"character_id": "__identity__",
	"skill_vnum": "U16",
	"life_sequence": "U32",
	"remaining_ticks": "U32",
	"paused": "Bool"
}

## 1. id: String[br]
## 2. account: PackedByteArray[br]
## 3. character_id: PackedByteArray[br]
## 4. skill_vnum: int[br]
## 5. life_sequence: int[br]
## 6. remaining_ticks: int[br]
## 7. paused: bool[br]
static func create(p_id: String, p_account: PackedByteArray, p_character_id: PackedByteArray, p_skill_vnum: int, p_life_sequence: int, p_remaining_ticks: int, p_paused: bool) -> GameBuffStatus:
	var result: GameBuffStatus = GameBuffStatus.new()
	result.id = p_id
	result.account = p_account
	result.character_id = p_character_id
	result.skill_vnum = p_skill_vnum
	result.life_sequence = p_life_sequence
	result.remaining_ticks = p_remaining_ticks
	result.paused = p_paused
	return result
