# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameSession extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var connection_id: PackedByteArray
@export var identity: PackedByteArray

#BSATN metadata
const primary_key: StringName = &'connection_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"connection_id": "__connection_id__",
	"identity": "__identity__"
}

## 1. connection_id: PackedByteArray[br]
## 2. identity: PackedByteArray[br]
static func create(p_connection_id: PackedByteArray, p_identity: PackedByteArray) -> GameSession:
	var result: GameSession = GameSession.new()
	result.connection_id = p_connection_id
	result.identity = p_identity
	return result
