# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GamePendingSkill extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var character_id: PackedByteArray
@export var connection_id: PackedByteArray
@export var skill_vnum: int
@export var rank: int
@export var action_revision: int
@export var source_life: int
@export var hit_at_us: int
@export var hit_until_us: int
@export var attacker: GameCapturedPlayerAttacker
@export var vitality: int
@export var hit_lives: Array[String]

#BSATN metadata
const primary_key: StringName = &'character_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"character_id": "__identity__",
	"connection_id": "__connection_id__",
	"skill_vnum": "U16",
	"rank": "U8",
	"action_revision": "U64",
	"source_life": "U32",
	"hit_at_us": "I64",
	"hit_until_us": "I64",
	"attacker": "GameCapturedPlayerAttacker",
	"vitality": "U8",
	"hit_lives": "vec_String"
}

## 1. character_id: PackedByteArray[br]
## 2. connection_id: PackedByteArray[br]
## 3. skill_vnum: int[br]
## 4. rank: int[br]
## 5. action_revision: int[br]
## 6. source_life: int[br]
## 7. hit_at_us: int[br]
## 8. hit_until_us: int[br]
## 9. attacker: GameCapturedPlayerAttacker[br]
## 10. vitality: int[br]
## 11. hit_lives: Array[String][br]
static func create(p_character_id: PackedByteArray, p_connection_id: PackedByteArray, p_skill_vnum: int, p_rank: int, p_action_revision: int, p_source_life: int, p_hit_at_us: int, p_hit_until_us: int, p_attacker: GameCapturedPlayerAttacker, p_vitality: int, p_hit_lives: Array[String]) -> GamePendingSkill:
	var result: GamePendingSkill = GamePendingSkill.new()
	result.character_id = p_character_id
	result.connection_id = p_connection_id
	result.skill_vnum = p_skill_vnum
	result.rank = p_rank
	result.action_revision = p_action_revision
	result.source_life = p_source_life
	result.hit_at_us = p_hit_at_us
	result.hit_until_us = p_hit_until_us
	result.attacker = p_attacker
	result.vitality = p_vitality
	result.hit_lives = p_hit_lives
	return result
