# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameCapturedPlayerAttacker extends Resource

const module_name : String = "Game"
const table_names: Array[String] = []

@export var level: int
@export var strength: int
@export var dexterity: int
@export var stat_attack: int
@export var equipped_item_id: int
@export var equipped_vnum: int

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"level": "U8",
	"strength": "U8",
	"dexterity": "U8",
	"stat_attack": "I32",
	"equipped_item_id": "U64",
	"equipped_vnum": "U32"
}

## 1. level: int[br]
## 2. strength: int[br]
## 3. dexterity: int[br]
## 4. stat_attack: int[br]
## 5. equipped_item_id: int[br]
## 6. equipped_vnum: int[br]
static func create(p_level: int, p_strength: int, p_dexterity: int, p_stat_attack: int, p_equipped_item_id: int, p_equipped_vnum: int) -> GameCapturedPlayerAttacker:
	var result: GameCapturedPlayerAttacker = GameCapturedPlayerAttacker.new()
	result.level = p_level
	result.strength = p_strength
	result.dexterity = p_dexterity
	result.stat_attack = p_stat_attack
	result.equipped_item_id = p_equipped_item_id
	result.equipped_vnum = p_equipped_vnum
	return result
