# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameAdminRequestReceipt extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var request_id: String
@export var actor_account: PackedByteArray
@export var action: String
@export var canonical_argument: String
@export var target_account: PackedByteArray
@export var target_character: PackedByteArray
@export var outcome: String
@export var reason_code: String
@export var severity: String
@export var message: String
@export var created_at: int
@export var audit_id: int
@export var applied_experience: int

#BSATN metadata
const primary_key: StringName = &'request_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"request_id": "String",
	"actor_account": "__identity__",
	"action": "String",
	"canonical_argument": "String",
	"target_account": "__identity__",
	"target_character": "__identity__",
	"outcome": "String",
	"reason_code": "String",
	"severity": "String",
	"message": "String",
	"created_at": "__timestamp_micros_since_unix_epoch__",
	"audit_id": "U64",
	"applied_experience": "U64"
}

## 1. request_id: String[br]
## 2. actor_account: PackedByteArray[br]
## 3. action: String[br]
## 4. canonical_argument: String[br]
## 5. target_account: PackedByteArray[br]
## 6. target_character: PackedByteArray[br]
## 7. outcome: String[br]
## 8. reason_code: String[br]
## 9. severity: String[br]
## 10. message: String[br]
## 11. created_at: int[br]
## 12. audit_id: int[br]
## 13. applied_experience: int[br]
static func create(p_request_id: String, p_actor_account: PackedByteArray, p_action: String, p_canonical_argument: String, p_target_account: PackedByteArray, p_target_character: PackedByteArray, p_outcome: String, p_reason_code: String, p_severity: String, p_message: String, p_created_at: int, p_audit_id: int, p_applied_experience: int) -> GameAdminRequestReceipt:
	var result: GameAdminRequestReceipt = GameAdminRequestReceipt.new()
	result.request_id = p_request_id
	result.actor_account = p_actor_account
	result.action = p_action
	result.canonical_argument = p_canonical_argument
	result.target_account = p_target_account
	result.target_character = p_target_character
	result.outcome = p_outcome
	result.reason_code = p_reason_code
	result.severity = p_severity
	result.message = p_message
	result.created_at = p_created_at
	result.audit_id = p_audit_id
	result.applied_experience = p_applied_experience
	return result
