# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameInventoryItem extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['inventory_item']

@export var id: int
@export var owner: PackedByteArray
@export var account: PackedByteArray
@export var vnum: int
@export var count: int
@export var cell: int
@export var equipped: bool

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"owner": "__identity__",
	"account": "__identity__",
	"vnum": "U32",
	"count": "U16",
	"cell": "U8",
	"equipped": "Bool"
}

## 1. id: int[br]
## 2. owner: PackedByteArray[br]
## 3. account: PackedByteArray[br]
## 4. vnum: int[br]
## 5. count: int[br]
## 6. cell: int[br]
## 7. equipped: bool[br]
static func create(p_id: int, p_owner: PackedByteArray, p_account: PackedByteArray, p_vnum: int, p_count: int, p_cell: int, p_equipped: bool) -> GameInventoryItem:
	var result: GameInventoryItem = GameInventoryItem.new()
	result.id = p_id
	result.owner = p_owner
	result.account = p_account
	result.vnum = p_vnum
	result.count = p_count
	result.cell = p_cell
	result.equipped = p_equipped
	return result
