# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterAllocationCursor extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var id: int
@export var last_issued: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U8",
	"last_issued": "U32"
}

## 1. id: int[br]
## 2. last_issued: int[br]
static func create(p_id: int, p_last_issued: int) -> GameMonsterAllocationCursor:
	var result: GameMonsterAllocationCursor = GameMonsterAllocationCursor.new()
	result.id = p_id
	result.last_issued = p_last_issued
	return result
