# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GamePlayer extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['player']

@export var identity: PackedByteArray
@export var name: String
@export var x: float
@export var y: float
@export var z: float
@export var heading: float
@export var activity: int
@export var online: bool
@export var attack_sequence: int
@export var attack_speed_percent: int
@export var life_sequence: int
@export var health: int
@export var max_health: int
@export var gold: int
@export var respawn_at_us: int
@export var attack_action_id: String
@export var action_started_at_us: int
@export var action_ends_at_us: int

#BSATN metadata
const primary_key: StringName = &'identity'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"identity": "__identity__",
	"name": "String",
	"x": "F32",
	"y": "F32",
	"z": "F32",
	"heading": "F32",
	"activity": "U8",
	"online": "Bool",
	"attack_sequence": "U32",
	"attack_speed_percent": "U16",
	"life_sequence": "U32",
	"health": "U16",
	"max_health": "U16",
	"gold": "U32",
	"respawn_at_us": "I64",
	"attack_action_id": "String",
	"action_started_at_us": "I64",
	"action_ends_at_us": "I64"
}

## 1. identity: PackedByteArray[br]
## 2. name: String[br]
## 3. x: float[br]
## 4. y: float[br]
## 5. z: float[br]
## 6. heading: float[br]
## 7. activity: int[br]
## 8. online: bool[br]
## 9. attack_sequence: int[br]
## 10. attack_speed_percent: int[br]
## 11. life_sequence: int[br]
## 12. health: int[br]
## 13. max_health: int[br]
## 14. gold: int[br]
## 15. respawn_at_us: int[br]
## 16. attack_action_id: String[br]
## 17. action_started_at_us: int[br]
## 18. action_ends_at_us: int[br]
static func create(p_identity: PackedByteArray, p_name: String, p_x: float, p_y: float, p_z: float, p_heading: float, p_activity: int, p_online: bool, p_attack_sequence: int, p_attack_speed_percent: int, p_life_sequence: int, p_health: int, p_max_health: int, p_gold: int, p_respawn_at_us: int, p_attack_action_id: String, p_action_started_at_us: int, p_action_ends_at_us: int) -> GamePlayer:
	var result: GamePlayer = GamePlayer.new()
	result.identity = p_identity
	result.name = p_name
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.heading = p_heading
	result.activity = p_activity
	result.online = p_online
	result.attack_sequence = p_attack_sequence
	result.attack_speed_percent = p_attack_speed_percent
	result.life_sequence = p_life_sequence
	result.health = p_health
	result.max_health = p_max_health
	result.gold = p_gold
	result.respawn_at_us = p_respawn_at_us
	result.attack_action_id = p_attack_action_id
	result.action_started_at_us = p_action_started_at_us
	result.action_ends_at_us = p_action_ends_at_us
	return result
