# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameMonsterVictim extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var monster_id: int
@export var monster_life: int
@export var character_id: PackedByteArray
@export var character_life: int
@export var last_set_us: int
@export var maximum: int

#BSATN metadata
const primary_key: StringName = &'monster_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"monster_id": "U32",
	"monster_life": "U32",
	"character_id": "__identity__",
	"character_life": "U32",
	"last_set_us": "I64",
	"maximum": "I32"
}

## 1. monster_id: int[br]
## 2. monster_life: int[br]
## 3. character_id: PackedByteArray[br]
## 4. character_life: int[br]
## 5. last_set_us: int[br]
## 6. maximum: int[br]
static func create(p_monster_id: int, p_monster_life: int, p_character_id: PackedByteArray, p_character_life: int, p_last_set_us: int, p_maximum: int) -> GameMonsterVictim:
	var result: GameMonsterVictim = GameMonsterVictim.new()
	result.monster_id = p_monster_id
	result.monster_life = p_monster_life
	result.character_id = p_character_id
	result.character_life = p_character_life
	result.last_set_us = p_last_set_us
	result.maximum = p_maximum
	return result
