# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameLoot extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = ['loot']

@export var id: int
@export var x: float
@export var y: float
@export var z: float
@export var gold: int
@export var owner: PackedByteArray
@export var reserved_until_us: int
@export var expires_at_us: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"x": "F32",
	"y": "F32",
	"z": "F32",
	"gold": "U32",
	"owner": "__identity__",
	"reserved_until_us": "I64",
	"expires_at_us": "I64"
}

## 1. id: int[br]
## 2. x: float[br]
## 3. y: float[br]
## 4. z: float[br]
## 5. gold: int[br]
## 6. owner: PackedByteArray[br]
## 7. reserved_until_us: int[br]
## 8. expires_at_us: int[br]
static func create(p_id: int, p_x: float, p_y: float, p_z: float, p_gold: int, p_owner: PackedByteArray, p_reserved_until_us: int, p_expires_at_us: int) -> GameLoot:
	var result: GameLoot = GameLoot.new()
	result.id = p_id
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.gold = p_gold
	result.owner = p_owner
	result.reserved_until_us = p_reserved_until_us
	result.expires_at_us = p_expires_at_us
	return result
