# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name GameProgressionOperator extends _ModuleTableType

const module_name : String = "Game"
const table_names: Array[String] = []

@export var account: PackedByteArray
@export var enabled: bool
@export var changed_by: PackedByteArray
@export var changed_at: int
@export var audit_id: int

#BSATN metadata
const primary_key: StringName = &'account'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"account": "__identity__",
	"enabled": "Bool",
	"changed_by": "__identity__",
	"changed_at": "__timestamp_micros_since_unix_epoch__",
	"audit_id": "U64"
}

## 1. account: PackedByteArray[br]
## 2. enabled: bool[br]
## 3. changed_by: PackedByteArray[br]
## 4. changed_at: int[br]
## 5. audit_id: int[br]
static func create(p_account: PackedByteArray, p_enabled: bool, p_changed_by: PackedByteArray, p_changed_at: int, p_audit_id: int) -> GameProgressionOperator:
	var result: GameProgressionOperator = GameProgressionOperator.new()
	result.account = p_account
	result.enabled = p_enabled
	result.changed_by = p_changed_by
	result.changed_at = p_changed_at
	result.audit_id = p_audit_id
	return result
