@tool
class_name SpacetimeCodegen extends Resource

const REQUIRED_FOLDERS_IN_CODEGEN_FOLDER: Array[String] = ["tables", "types"]
const OPTION_CLASS_NAME := "Option"
const AUTOGENERATED_COMMENT := "# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS\n" + \
	"# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.\n"

var _plugin_config: SpacetimeDBPluginConfig
var _schema_path: String


func _init(p_schema_path: String) -> void:
	_schema_path = p_schema_path


func _ensure_dir(path: String) -> void:
	if not DirAccess.dir_exists_absolute(path):
		DirAccess.make_dir_recursive_absolute(path)


func _write_text(path: String, body: String) -> void:
	var handle := FileAccess.open(path, FileAccess.WRITE)
	if handle:
		handle.store_string(body)
		handle.close()


func _gd_type(schema: SpacetimeParsedSchema, raw_name: String, member_def: Dictionary = {}) -> String:
	if member_def.has("godot_type_hint") and not String(member_def.get("godot_type_hint", "")).is_empty():
		return String(member_def.get("godot_type_hint", "Variant"))

	for type_def in schema.types:
		if type_def.get("name", "") == raw_name:
			if type_def.has("godot_type_hint"):
				return String(type_def.get("godot_type_hint", raw_name))
			break

	return raw_name if not raw_name.is_empty() else "Variant"


func _member_gd_type(schema: SpacetimeParsedSchema, member_def: Dictionary) -> String:
	var raw_name: String = String(member_def.get("type", "Variant"))

	if member_def.has("is_option"):
		return OPTION_CLASS_NAME

	if member_def.has("is_array"):
		var item_type := _gd_type(schema, raw_name, member_def)
		if member_def.has("is_option_inside_array"):
			item_type = OPTION_CLASS_NAME
		return "Array[%s]" % item_type

	return _gd_type(schema, raw_name, member_def)


func _param_bsatn_literal(raw_type: String) -> String:
	return "''" if raw_type.is_empty() else "&'%s'" % raw_type


func generate_bindings() -> Array[String]:
	var generated_files: Array[String] = []

	for module_name: String in _plugin_config.module_configs:
		generated_files.append_array(_generate_module_bindings(module_name))

	var autoload_content := _generate_autoload_gdscript(
		_plugin_config.module_configs.keys()
	)
	var autoload_output_file_path := "%s/%s" % [
		_schema_path,
		SpacetimePlugin.AUTOLOAD_FILE_NAME,
	]
	_write_text(autoload_output_file_path, autoload_content)
	generated_files.append(autoload_output_file_path)

	SpacetimePlugin.print_log("Generated files:")
	for generated_file in generated_files:
		SpacetimePlugin.print_log(generated_file)

	return generated_files


func _generate_module_bindings(module_name: String) -> Array[String]:
	var debug_dir_path := "%s/%s" % [SpacetimePlugin.BINDINGS_PATH, "codegen_debug"]
	_ensure_dir(debug_dir_path)

	_write_text(
		"%s/readme.txt" % debug_dir_path,
		"You can delete this directory and files. It's only used for codegen debugging.",
	)

	var parsed_json = JSON.parse_string(
		_plugin_config.module_configs[module_name].unparsed_module_schema
	)

	_write_text(
		"%s/unparsed_schema_%s.json" % [debug_dir_path, module_name],
		JSON.stringify(parsed_json, "\t", false),
	)

	var parsed_schema := SpacetimeSchemaParser.parse_schema(parsed_json, module_name)
	_plugin_config.module_configs[module_name].unparsed_module_schema = ""
	_plugin_config.module_configs[module_name].parsed_schema = parsed_schema

	if parsed_schema.is_empty():
		SpacetimePlugin.print_err(
			"Schema parsing failed for module: %s. Aborting codegen for this module."
			% module_name
		)
		return []

	_write_text(
		"%s/schema_%s.json" % [debug_dir_path, module_name],
		JSON.stringify(parsed_schema.to_dictionary(), "\t", false),
	)

	for folder_name in REQUIRED_FOLDERS_IN_CODEGEN_FOLDER:
		_ensure_dir("%s/%s" % [_schema_path, folder_name])

	SpacetimePlugin.print_log("schema files saved")
	return _generate_gdscript_from_schema(module_name, parsed_schema)


func _generate_gdscript_from_schema(
	module_name: String,
	schema: SpacetimeParsedSchema
) -> Array[String]:
	var generated_files: Array[String] = []

	for type_def in schema.types:
		if SpacetimeSchemaParser.GDNATIVE_ARRAYLIKE_TYPES.has(type_def.get("name")):
			continue

		var content := ""
		if type_def.has("struct"):
			var table_names_to_emit: Array[String] = []
			if type_def.has("table_names"):
				var table_names_arr: Array = type_def.get("table_names", [])
				for i in table_names_arr.size():
					var table_name: String = table_names_arr[i]
					if _plugin_config.module_configs[module_name].hide_private_tables and not type_def.get("is_public", [])[i]:
						SpacetimePlugin.print_log("Skipping private table %s" % table_name)
						continue
					table_names_to_emit.append(table_name)

			content = _generate_struct_gdscript(schema, type_def, table_names_to_emit)
		elif type_def.has("enum"):
			content = _generate_enum_gdscript(schema, type_def)
		else:
			continue

		var output_file_name := "%s.gd" % [
			type_def.get("name", "").to_snake_case(),
		]
		var folder_path := "%s/types" % _schema_path
		_ensure_dir(folder_path)

		var output_file_path := "%s/%s" % [folder_path, output_file_name]
		_write_text(output_file_path, content)
		generated_files.append(output_file_path)

	for table_def in schema.tables:
		var table_name = table_def.get("name", null)
		if table_name == null:
			continue
		if _plugin_config.module_configs[module_name].hide_private_tables and not table_def.get("is_public", true):
			SpacetimePlugin.print_log("Skipping private table: %s" % table_name)
			continue

		for unique_index_def in table_def.get("unique_indexes", []):
			var index_content := _generate_table_unique_index_gdscript(
				schema,
				unique_index_def,
				table_def
			)
			var index_file_name := "%s_%s_unique_index.gd" % [
				table_name.to_snake_case(),
				unique_index_def.get("name", "").to_snake_case(),
			]
			var index_folder := "%s/tables" % _schema_path
			_ensure_dir(index_folder)

			var index_path := "%s/%s" % [index_folder, index_file_name]
			_write_text(index_path, index_content)
			generated_files.append(index_path)

		var table_content := _generate_table_gdscript(schema, table_def)
		var table_file_name := "%s_table.gd" % [
			table_name.to_snake_case(),
		]
		var table_folder := "%s/tables" % _schema_path
		_ensure_dir(table_folder)

		var table_path := "%s/%s" % [table_folder, table_file_name]
		_write_text(table_path, table_content)
		generated_files.append(table_path)

	var module_client_content := _generate_module_client_gdscript(module_name, schema)
	var module_client_file_name := "module_%s_client.gd" % schema.module.to_snake_case()
	var module_client_path := "%s/%s" % [_schema_path, module_client_file_name]
	_write_text(module_client_path, module_client_content)
	generated_files.append(module_client_path)

	var db_content := _generate_db_gdscript(module_name, schema)
	var db_file_name := "module_%s_db.gd" % schema.module.to_snake_case()
	var db_path := "%s/%s" % [_schema_path, db_file_name]
	_write_text(db_path, db_content)
	generated_files.append(db_path)

	var reducers_content := _generate_reducers_gdscript(module_name, schema)
	var reducers_file_name := "module_%s_reducers.gd" % schema.module.to_snake_case()
	var reducers_path := "%s/%s" % [_schema_path, reducers_file_name]
	_write_text(reducers_path, reducers_content)
	generated_files.append(reducers_path)

	var procedures_content := _generate_procedures_gdscript(module_name, schema)
	var procedures_file_name := "module_%s_procedures.gd" % schema.module.to_snake_case()
	var procedures_path := "%s/%s" % [_schema_path, procedures_file_name]
	_write_text(procedures_path, procedures_content)
	generated_files.append(procedures_path)

	var types_content := _generate_types_gdscript(module_name, schema)
	var types_file_name := "module_%s_types.gd" % schema.module.to_snake_case()
	var types_path := "%s/%s" % [_schema_path, types_file_name]
	_write_text(types_path, types_content)
	generated_files.append(types_path)

	return generated_files


func _generate_table_unique_index_gdscript(
	schema: SpacetimeParsedSchema,
	unique_index_def: Dictionary,
	table_def: Dictionary
) -> String:
	var table_name: String = table_def.get("name", "")
	var field_name: String = unique_index_def.get("name", "")
	var field_type: String = _gd_type(schema, unique_index_def.get("type", "Variant"), unique_index_def)
	var type_def: Dictionary = schema.types[table_def.get("type_idx")] if table_def.has("type_idx") else {}
	var type_name: String = _gd_type(schema, type_def.get("name", "Variant"), type_def)

	var class_name_text := "%s%sUniqueIndex" % [
		table_name.to_pascal_case(),
		field_name.to_pascal_case(),
	]

	return AUTOGENERATED_COMMENT + \
		"class_name %s extends _ModuleTableUniqueIndex\n\n" % class_name_text + \
		"var _cache: Dictionary[%s, %s] = {}\n\n" % [field_type, type_name] + \
		"func _init() -> void:\n" + \
		"\tset_meta(\"table_name\", \"%s\")\n" % table_name.to_snake_case().trim_prefix(schema.module.to_snake_case() + "_") + \
		"\tset_meta(\"field_name\", \"%s\")\n\n" % field_name + \
		"static func create(p_local_db: LocalDatabase) -> %s:\n" % class_name_text + \
		"\tvar index: %s = %s.new()\n" % [class_name_text, class_name_text] + \
		"\tindex._connect_cache_to_db(index._cache, p_local_db)\n" + \
		"\treturn index\n\n" + \
		"func find(col_val: %s) -> %s:\n" % [field_type, type_name] + \
		"\treturn _cache.get(col_val, null)\n"


func _generate_table_gdscript(
	schema: SpacetimeParsedSchema,
	table_def: Dictionary
) -> String:
	var table_name: String = table_def.get("name", "")
	var type_def: Dictionary = schema.types[table_def.get("type_idx")] if table_def.has("type_idx") else {}
	var type_name: String = _gd_type(schema, type_def.get("name", "Variant"), type_def)

	var unique_index_classes: Dictionary[String, String] = {}
	for unique_index_def in table_def.get("unique_indexes", []):
		var field_name: String = unique_index_def.get("name", "")
		unique_index_classes[field_name] = "%s%sUniqueIndex" % [
			table_name.to_pascal_case(),
			field_name.to_pascal_case(),
		]

	var class_name_text := "%sTable" % [
		table_name.to_pascal_case(),
	]

	var content := AUTOGENERATED_COMMENT + \
		"class_name %s extends _ModuleTable\n\n" % class_name_text

	for field_name in unique_index_classes:
		content += "var %s: %s\n" % [field_name, unique_index_classes[field_name]]
	content += "\nfunc _init() -> void:\n" + \
		"\tset_meta(\"table_name\", \"%s\")\n" % table_name.to_snake_case().trim_prefix(schema.module.to_snake_case() + "_") + \
		"\tset_meta(\"is_event\", \"%s\")\n" % table_def.get("is_event") + \
		"\tset_meta(\"type\", \"%s\")\n" % type_name

	content += "\nstatic func create(p_local_db: LocalDatabase) -> %s:\n" % class_name_text + \
		"\tvar table: %s = %s.new()\n" % [class_name_text, class_name_text] + \
		"\ttable._db = p_local_db\n"

	for field_name in unique_index_classes:
		content += "\ttable.%s = %s.create(p_local_db)\n" % [
			field_name,
			unique_index_classes[field_name],
		]
	content += "\treturn table\n"

	content += "\nfunc iter() -> Array[%s]:\n" % type_name + \
		"\tvar rows: Array = super()\n" + \
		"\tvar typed_array: Array[%s] = []\n" % type_name + \
		"\ttyped_array.assign(rows)\n" + \
		"\treturn typed_array\n"

	return content


func _generate_struct_gdscript(
	schema: SpacetimeParsedSchema,
	type_def: Dictionary,
	table_names: Array[String]
) -> String:
	var struct_name: String = type_def.get("name", "")
	var fields: Array = type_def.get("struct", [])
	var meta_dict: Dictionary[StringName, StringName] = {}
	var table_name: String = type_def.get("table_names", [""]).get(0)
	var class_name_text := struct_name.to_pascal_case()
	var base_class := "Resource"
	var pk_line := "const primary_key: StringName = &''\n"


	if not table_name.is_empty():
		base_class = "_ModuleTableType"
		var primary_key_name: String = type_def.get("primary_key_name", "")
		pk_line = "const primary_key: StringName = &'%s'\n" % primary_key_name

	var content := AUTOGENERATED_COMMENT + \
		"@tool\n" + \
		"class_name %s extends %s\n\n" % [class_name_text, base_class]

	content += "const module_name : String = \"%s\"\n" % schema.module + \
		"const table_names: Array[String] = [%s]\n\n" % \
		[", ".join(table_names.map(func(x): return "'%s'" % x))]

	var class_fields: Array = []
	var create_doc := ""
	var count := 0
	for prop: Dictionary in fields:
		count += 1
		var field_name: String = prop.get("name", "")
		var bsatn_type: String = prop.get("type", "")
		var godot_type_hint : String = prop.get("godot_type_hint", "Variant")
		if field_name == "scheduled_at":
			bsatn_type = "scheduled_at"
		create_doc += "## %d. %s: %s[br]\n" % [count,field_name,godot_type_hint]
		meta_dict.set(field_name, bsatn_type)

		content += "@export var %s: %s\n" % [field_name, godot_type_hint]
		class_fields.append([field_name, godot_type_hint])

	content += "\n#BSATN metadata\n"
	content += pk_line
	content += "const BSATN_TYPES: Dictionary[StringName, StringName] = "
	content += JSON.stringify(meta_dict, "\t", false)

	content += "\n\n" + create_doc
	content += "static func create(%s) -> %s:\n" % [
		", ".join(class_fields.map(func(x): return "p_%s: %s" % [x[0], x[1]])),
		class_name_text,
	]
	content += "\tvar result: %s = %s.new()\n" % [class_name_text, class_name_text]
	for field_data in class_fields:
		content += "\tresult.%s = p_%s\n" % [field_data[0], field_data[0]]
	content += "\treturn result\n"
	return content


func _generate_enum_gdscript(
	schema: SpacetimeParsedSchema,
	type_def: Dictionary
) -> String:
	var enum_name: String = type_def.get("name", "")
	var variants: Array = type_def.get("enum", [])
	var class_name_text := enum_name.to_pascal_case()

	var variant_lines := "\n".join(variants.map(func(x): return "\t%s," % x.get("name", "")))

	var content := AUTOGENERATED_COMMENT + \
		"class_name %s extends RustEnum\n\n" % class_name_text + \
		"enum Options {\n%s\n}\n\n" % variant_lines + \

		"const enum_options: Array[StringName] = [%s]\n" % [ \
			", ".join(variants.map(func(x):
				var raw_name: String = x.get("type", "")
				var rust_name := raw_name
				return "&'%s'" % rust_name if not rust_name.is_empty() else "''" \
			))
		] + \
		"const bsatn_enum_type: StringName = &'%s'\n\n" % class_name_text + \
		"static func parse_enum_name(i: int) -> String:\n\tmatch i:\n"

	for i in range(variants.size()):
		content += "\t\t%d: return &'%s'\n" % [i, variants[i].get("name", "")]
	content += "\t\t_:\n\t\t\tprinterr(\"Enum does not have value for %d. This is out of bounds.\" % i)\n\t\t\treturn &'Unknown'\n\n"

	var get_funcs: Array[String] = []
	var create_funcs: Array[String] = []

	for variant_def in variants:
		var variant_name: String = variant_def.get("name", "")
		var variant_type: String = _gd_type(schema, variant_def.get("type", "Variant"), variant_def)
		var nested_parts: Array = variant_def.get("nested_type", []).duplicate()
		nested_parts.append(variant_type)
#
		if variant_def.has("is_option"):
			variant_type = OPTION_CLASS_NAME
		elif variant_def.has("is_array"):
			if variant_def.has("is_option_inside_array"):
				variant_type = OPTION_CLASS_NAME
			variant_type = "Array[%s]" % variant_type

		if variant_def.has("type"):
			if variant_def.has("is_option") or variant_def.has("is_option_inside_array"):
				get_funcs.append("## Returns: %s\n" % " of ".join(nested_parts))
				create_funcs.append("## 0. data: %s\n" % " of ".join(nested_parts))
			get_funcs.append(
				"func get_%s() -> %s:\n\treturn data\n\n" % [
					variant_name.to_snake_case(),
					variant_type,
				]
			)
			create_funcs.append(
				"static func create_%s(_data: %s) -> %s:\n\treturn create(Options.%s, _data)\n\n"
				% [
					variant_name.to_snake_case(),
					variant_type,
					class_name_text,
					variant_name,
				]
			)
		else:
			create_funcs.append(
				"static func create_%s() -> %s:\n\treturn create(Options.%s)\n\n"
				% [variant_name.to_snake_case(), class_name_text, variant_name]
			)

	content += "".join(get_funcs)
	content += "static func create(p_type: int, p_data: Variant = null) -> %s:\n" % class_name_text + \
		"\tvar result : %s = %s.new()\n" % [class_name_text, class_name_text] + \
		"\tresult.value = p_type\n" + \
		"\tresult.data = p_data\n" + \
		"\treturn result\n\n"
	content += "".join(create_funcs)
	return content


func _generate_module_client_gdscript(
	module_name: String,
	schema: SpacetimeParsedSchema
) -> String:
	var content := AUTOGENERATED_COMMENT + \
		"@tool\n" + \
		"class_name %sModuleClient extends SpacetimeDBClient\n\n" % schema.module.to_pascal_case() + \
		"const Types = preload('%s/module_%s_types.gd')\n\n" % [
			_schema_path,
			schema.module.to_snake_case(),
		]

	var types_part := _generate_types_gdscript(module_name, schema, true)
	if not types_part.is_empty():
		content += types_part + "\n"

	content += "\nvar reducers: %sModuleReducers\n" % schema.module.to_pascal_case() + \
		"var procedures: %sModuleProcedures\n" % schema.module.to_pascal_case() + \
		"var db: %sModuleDb\n\n" % schema.module.to_pascal_case() + \
		"func _init() -> void:\n" + \
		"\tset_meta(\"module_name\", \"%s\")\n" % schema.module + \
		"\tname = \"%sModule\"\n" % schema.module.to_pascal_case() + \
		"\treducers = preload('%s/module_%s_reducers.gd').new(self)\n" % [
			_schema_path,
			schema.module.to_snake_case(),
		] + \
		"\tprocedures = preload('%s/module_%s_procedures.gd').new(self)\n" % [
			_schema_path,
			schema.module.to_snake_case(),
		] + \
		"\nfunc _init_db(p_local_db: LocalDatabase) -> void:\n" + \
		"\tdb = preload('%s/module_%s_db.gd').new(p_local_db)\n" % [
			_schema_path,
			schema.module.to_snake_case(),
		]

	return content


func _generate_db_gdscript(
	module_name: String,
	schema: SpacetimeParsedSchema
) -> String:
	var tables: Array = []
	for table_def in schema.tables:
		var table_name = table_def.get("name", null)
		if table_name == null:
			continue
		if _plugin_config.module_configs[module_name].hide_private_tables and not table_def.get("is_public", true):
			continue
		tables.append( ["%sTable" % table_name.to_pascal_case(), \
			"%s" % table_name.to_snake_case().trim_prefix(schema.module.to_snake_case()+"_")])
	var content := AUTOGENERATED_COMMENT + \
		"class_name %sModuleDb extends RefCounted\n\n" % schema.module.to_pascal_case() + \
		"const table_names : Array[String] = [%s]\n\n" % ", ".join(tables.map(func(t)-> String: return '"'+t[1]+'"'))

	for table_name in tables:
		content += "var %s: %s\n" % [table_name[1], table_name[0]]
	print()
	content += "\nfunc _init(p_local_db: LocalDatabase) -> void:\n"
	if tables.is_empty():
		content += "\tpass\n"
	for table_name in tables:
		content += "\t%s = preload('%s/tables/%s_table.gd').create(p_local_db)\n" % [
			table_name[1],
			_schema_path,
			schema.module.to_snake_case()+"_"+table_name[1],
		]

	return content


func _generate_types_gdscript(
	module_name: String,
	schema: SpacetimeParsedSchema,
	const_pointer: bool = false
) -> String:
	var content := "" if const_pointer else AUTOGENERATED_COMMENT + "\n"

	for type_def in schema.types:
		if SpacetimeSchemaParser.GDNATIVE_ARRAYLIKE_TYPES.has(type_def.get("name")):
			continue

		var type_name: String = type_def.get("name", "")
		if type_def.has("table_name"):
			if _plugin_config.module_configs[module_name].hide_private_tables and not type_def.get("is_public", []).has(true):
				continue

		if const_pointer:
			content += "const %s = Types.%s\n" % [
				type_name.to_pascal_case().trim_prefix(module_name.to_pascal_case()),
				type_name.to_pascal_case().trim_prefix(module_name.to_pascal_case()),
			]
		else:
			content += "const %s = preload('%s/types/%s.gd')\n" % [
				type_name.to_pascal_case().trim_prefix(module_name.to_pascal_case()),
				_schema_path,
				type_name.to_snake_case(),
			]

	return content


func _generate_reducers_gdscript(
	module_name: String,
	schema: SpacetimeParsedSchema
) -> String:
	var content := AUTOGENERATED_COMMENT + \
		"class_name %sModuleReducers extends RefCounted\n\n" % schema.module.to_pascal_case() + \
		"var _client: SpacetimeDBClient\n\n" + \
		"func _init(p_client: SpacetimeDBClient) -> void:\n\t_client = p_client\n"

	for reducer_def in schema.reducers:
		var params_str_parts: Array[String] = []
		var description_comment: Array[String] = []
		var reducer_params: Array = reducer_def.get("params", [])

		for i in reducer_params.size():
			var param_def: Dictionary = reducer_params[i]
			var param_name: String = param_def.get("name", "")
			var nested_parts: Array = param_def.get("nested_type", []).duplicate()
			nested_parts.append(_gd_type(schema, param_def.get("type", "Variant"), param_def))
			description_comment.append("## %d. %s: %s [br]" % [
				i,
				param_name,
				" of ".join(nested_parts),
			])

			params_str_parts.append("%s: %s" % [param_name, _member_gd_type(schema, param_def)])
		var params_str := ", ".join(params_str_parts)

		var param_names_list: Array = reducer_def.get("params", []).map(func(x): return x.get("name", ""))
		var param_names_str := ", ".join(param_names_list) if not param_names_list.is_empty() else ""

		var param_bsatn_types_list := (reducer_def.get("params", []) as Array).map(func(x):
			var ref_def: Dictionary = schema.types[x.type_idx] if x.has("type_idx") else {}
			var raw_name: String = x.get("type", "Variant")
			var raw_type := ""
			return _param_bsatn_literal(raw_name)
		)

		var param_bsatn_types_str := ", ".join(param_bsatn_types_list) if not param_bsatn_types_list.is_empty() else ""

		content += "\n".join(description_comment) + "\n"
		var reducer_name: String = reducer_def.get("name", "")
		var reducer_source_name: String = reducer_def.get("name", reducer_name)
		content += "func %s(%s) -> SpacetimeDBReducerCall:\n" % [reducer_name, params_str] + \
			"\treturn _client.call_reducer('%s', [%s], [%s])\n\n" % [
				reducer_source_name,
				param_names_str,
				param_bsatn_types_str,
			]

	return content


func _generate_procedures_gdscript(
	module_name: String,
	schema: SpacetimeParsedSchema
) -> String:
	var content := AUTOGENERATED_COMMENT + \
		"class_name %sModuleProcedures extends RefCounted\n\n" % schema.module.to_pascal_case() + \
		"var _client: SpacetimeDBClient\n\n" + \
		"func _init(p_client: SpacetimeDBClient) -> void:\n\t_client = p_client\n"

	for procedure_def in schema.procedures:
		var params_str_parts: Array[String] = []
		var description_comment: Array[String] = []
		var procedure_params: Array = procedure_def.get("params", [])

		for i in procedure_params.size():
			var param_def: Dictionary = procedure_params[i]
			var param_name: String = param_def.get("name", "")
			var nested_parts: Array = param_def.get("nested_type", []).duplicate()
			nested_parts.append(_gd_type(schema, param_def.get("type", "Variant"), param_def))
			description_comment.append("## %d. %s: %s [br]" % [
				i,
				param_name,
				" of ".join(nested_parts),
			])
			params_str_parts.append("%s: %s" % [param_name, _member_gd_type(schema, param_def)])

		var params_str := ", ".join(params_str_parts)
		var param_names_list: Array = procedure_def.get("params", []).map(func(x): return x.get("name", ""))
		var param_names_str := ", ".join(param_names_list) if not param_names_list.is_empty() else ""

		var param_bsatn_types_list := (procedure_def.get("params", []) as Array).map(func(x):
			var ref_def: Dictionary = schema.types[x.type_idx] if x.has("type_idx") else {}
			var raw_name: String = x.get("type", "Variant")
			return _param_bsatn_literal(raw_name)
		)
		var param_bsatn_types_str := ", ".join(param_bsatn_types_list) if not param_bsatn_types_list.is_empty() else ""

		var return_def: Dictionary = procedure_def.get("return_type", {})
		var return_name: String = return_def.get("type", "")

		content += "\n".join(description_comment) + "\n"
		var procedure_name: String = procedure_def.get("name", "")
		var procedure_source_name: String = procedure_def.get("name", procedure_name)
		content += "func %s(%s) -> SpacetimeDBProcedureCall:\n" % [procedure_name, params_str] + \
			"\treturn _client.call_procedure('%s', [%s], [%s], '%s')\n\n" % [
				procedure_source_name,
				param_names_str,
				param_bsatn_types_str,
				return_name,
			]

	return content


func _generate_autoload_gdscript(modules: Array[String]) -> String:
	var content := AUTOGENERATED_COMMENT + \
		"extends Node\n#SpacetimeDB Autoload\n\n"

	for module_name in modules:
		content += "var %s: %sModuleClient\n" % [
			module_name.to_pascal_case(),
			module_name.to_pascal_case(),
		]

	content += "\nfunc _init() -> void:\n"
	for module_name in modules:
		content += "\t%s = preload('%s/module_%s_client.gd').new()\n" % [
			module_name.to_pascal_case(),
			_schema_path,
			module_name.to_snake_case(),
		] + \
			"\tadd_child(%s)\n" % module_name.to_pascal_case()

	return content
