# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GamePlayerTable extends _ModuleTable

var identity: GamePlayerIdentityUniqueIndex

func _init() -> void:
	set_meta("table_name", "player")
	set_meta("is_event", "false")
	set_meta("type", "GamePlayer")

static func create(p_local_db: LocalDatabase) -> GamePlayerTable:
	var table: GamePlayerTable = GamePlayerTable.new()
	table._db = p_local_db
	table.identity = GamePlayerIdentityUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GamePlayer]:
	var rows: Array = super()
	var typed_array: Array[GamePlayer] = []
	typed_array.assign(rows)
	return typed_array
