# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameMonsterTable extends _ModuleTable

var id: GameMonsterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "monster")
	set_meta("is_event", "false")
	set_meta("type", "GameMonster")

static func create(p_local_db: LocalDatabase) -> GameMonsterTable:
	var table: GameMonsterTable = GameMonsterTable.new()
	table._db = p_local_db
	table.id = GameMonsterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameMonster]:
	var rows: Array = super()
	var typed_array: Array[GameMonster] = []
	typed_array.assign(rows)
	return typed_array
