# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameAccountCharacterCharacterIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, GameAccountCharacter] = {}

func _init() -> void:
	set_meta("table_name", "account_character")
	set_meta("field_name", "character_id")

static func create(p_local_db: LocalDatabase) -> GameAccountCharacterCharacterIdUniqueIndex:
	var index: GameAccountCharacterCharacterIdUniqueIndex = GameAccountCharacterCharacterIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: PackedByteArray) -> GameAccountCharacter:
	return _cache.get(col_val, null)
