# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameAccountStateAccountUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, GameAccountState] = {}

func _init() -> void:
	set_meta("table_name", "account_state")
	set_meta("field_name", "account")

static func create(p_local_db: LocalDatabase) -> GameAccountStateAccountUniqueIndex:
	var index: GameAccountStateAccountUniqueIndex = GameAccountStateAccountUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: PackedByteArray) -> GameAccountState:
	return _cache.get(col_val, null)
