# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameInventoryAccessTable extends _ModuleTable

var character_id: GameInventoryAccessCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "inventory_access")
	set_meta("is_event", "false")
	set_meta("type", "GameInventoryAccess")

static func create(p_local_db: LocalDatabase) -> GameInventoryAccessTable:
	var table: GameInventoryAccessTable = GameInventoryAccessTable.new()
	table._db = p_local_db
	table.character_id = GameInventoryAccessCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameInventoryAccess]:
	var rows: Array = super()
	var typed_array: Array[GameInventoryAccess] = []
	typed_array.assign(rows)
	return typed_array
