# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameQuestSelectionTable extends _ModuleTable

var character_id: GameQuestSelectionCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "quest_selection")
	set_meta("is_event", "false")
	set_meta("type", "GameQuestSelection")

static func create(p_local_db: LocalDatabase) -> GameQuestSelectionTable:
	var table: GameQuestSelectionTable = GameQuestSelectionTable.new()
	table._db = p_local_db
	table.character_id = GameQuestSelectionCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameQuestSelection]:
	var rows: Array = super()
	var typed_array: Array[GameQuestSelection] = []
	typed_array.assign(rows)
	return typed_array
