# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameQuestStateTable extends _ModuleTable

var id: GameQuestStateIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "quest_state")
	set_meta("is_event", "false")
	set_meta("type", "GameQuestState")

static func create(p_local_db: LocalDatabase) -> GameQuestStateTable:
	var table: GameQuestStateTable = GameQuestStateTable.new()
	table._db = p_local_db
	table.id = GameQuestStateIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameQuestState]:
	var rows: Array = super()
	var typed_array: Array[GameQuestState] = []
	typed_array.assign(rows)
	return typed_array
