# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameQuestObjectiveTable extends _ModuleTable

var id: GameQuestObjectiveIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "quest_objective")
	set_meta("is_event", "false")
	set_meta("type", "GameQuestObjective")

static func create(p_local_db: LocalDatabase) -> GameQuestObjectiveTable:
	var table: GameQuestObjectiveTable = GameQuestObjectiveTable.new()
	table._db = p_local_db
	table.id = GameQuestObjectiveIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameQuestObjective]:
	var rows: Array = super()
	var typed_array: Array[GameQuestObjective] = []
	typed_array.assign(rows)
	return typed_array
