# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameInventoryItemTable extends _ModuleTable

var id: GameInventoryItemIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "inventory_item")
	set_meta("is_event", "false")
	set_meta("type", "GameInventoryItem")

static func create(p_local_db: LocalDatabase) -> GameInventoryItemTable:
	var table: GameInventoryItemTable = GameInventoryItemTable.new()
	table._db = p_local_db
	table.id = GameInventoryItemIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameInventoryItem]:
	var rows: Array = super()
	var typed_array: Array[GameInventoryItem] = []
	typed_array.assign(rows)
	return typed_array
