# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameNpcInteractionSessionIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, GameNpcInteraction] = {}

func _init() -> void:
	set_meta("table_name", "npc_interaction")
	set_meta("field_name", "session_id")

static func create(p_local_db: LocalDatabase) -> GameNpcInteractionSessionIdUniqueIndex:
	var index: GameNpcInteractionSessionIdUniqueIndex = GameNpcInteractionSessionIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> GameNpcInteraction:
	return _cache.get(col_val, null)
