# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameWorldInfoTable extends _ModuleTable

var id: GameWorldInfoIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "world_info")
	set_meta("is_event", "false")
	set_meta("type", "GameWorldInfo")

static func create(p_local_db: LocalDatabase) -> GameWorldInfoTable:
	var table: GameWorldInfoTable = GameWorldInfoTable.new()
	table._db = p_local_db
	table.id = GameWorldInfoIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameWorldInfo]:
	var rows: Array = super()
	var typed_array: Array[GameWorldInfo] = []
	typed_array.assign(rows)
	return typed_array
