# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameMonsterStunMonsterIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, GameMonsterStun] = {}

func _init() -> void:
	set_meta("table_name", "monster_stun")
	set_meta("field_name", "monster_id")

static func create(p_local_db: LocalDatabase) -> GameMonsterStunMonsterIdUniqueIndex:
	var index: GameMonsterStunMonsterIdUniqueIndex = GameMonsterStunMonsterIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> GameMonsterStun:
	return _cache.get(col_val, null)
