# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameAccountCharacterTable extends _ModuleTable

var character_id: GameAccountCharacterCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "account_character")
	set_meta("is_event", "false")
	set_meta("type", "GameAccountCharacter")

static func create(p_local_db: LocalDatabase) -> GameAccountCharacterTable:
	var table: GameAccountCharacterTable = GameAccountCharacterTable.new()
	table._db = p_local_db
	table.character_id = GameAccountCharacterCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameAccountCharacter]:
	var rows: Array = super()
	var typed_array: Array[GameAccountCharacter] = []
	typed_array.assign(rows)
	return typed_array
