# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameCharacterProgressionTable extends _ModuleTable

var character_id: GameCharacterProgressionCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "character_progression")
	set_meta("is_event", "false")
	set_meta("type", "GameCharacterProgression")

static func create(p_local_db: LocalDatabase) -> GameCharacterProgressionTable:
	var table: GameCharacterProgressionTable = GameCharacterProgressionTable.new()
	table._db = p_local_db
	table.character_id = GameCharacterProgressionCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameCharacterProgression]:
	var rows: Array = super()
	var typed_array: Array[GameCharacterProgression] = []
	typed_array.assign(rows)
	return typed_array
