# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameNpcSpawnTable extends _ModuleTable

var spawn_id: GameNpcSpawnSpawnIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "npc_spawn")
	set_meta("is_event", "false")
	set_meta("type", "GameNpcSpawn")

static func create(p_local_db: LocalDatabase) -> GameNpcSpawnTable:
	var table: GameNpcSpawnTable = GameNpcSpawnTable.new()
	table._db = p_local_db
	table.spawn_id = GameNpcSpawnSpawnIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameNpcSpawn]:
	var rows: Array = super()
	var typed_array: Array[GameNpcSpawn] = []
	typed_array.assign(rows)
	return typed_array
