# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameCombatTargetViewTable extends _ModuleTable

var character_id: GameCombatTargetViewCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "combat_target_view")
	set_meta("is_event", "false")
	set_meta("type", "GameCombatTargetView")

static func create(p_local_db: LocalDatabase) -> GameCombatTargetViewTable:
	var table: GameCombatTargetViewTable = GameCombatTargetViewTable.new()
	table._db = p_local_db
	table.character_id = GameCombatTargetViewCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameCombatTargetView]:
	var rows: Array = super()
	var typed_array: Array[GameCombatTargetView] = []
	typed_array.assign(rows)
	return typed_array
