# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameQuestSelectionCharacterIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, GameQuestSelection] = {}

func _init() -> void:
	set_meta("table_name", "quest_selection")
	set_meta("field_name", "character_id")

static func create(p_local_db: LocalDatabase) -> GameQuestSelectionCharacterIdUniqueIndex:
	var index: GameQuestSelectionCharacterIdUniqueIndex = GameQuestSelectionCharacterIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: PackedByteArray) -> GameQuestSelection:
	return _cache.get(col_val, null)
