# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameBuffStatusTable extends _ModuleTable

var id: GameBuffStatusIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "buff_status")
	set_meta("is_event", "false")
	set_meta("type", "GameBuffStatus")

static func create(p_local_db: LocalDatabase) -> GameBuffStatusTable:
	var table: GameBuffStatusTable = GameBuffStatusTable.new()
	table._db = p_local_db
	table.id = GameBuffStatusIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameBuffStatus]:
	var rows: Array = super()
	var typed_array: Array[GameBuffStatus] = []
	typed_array.assign(rows)
	return typed_array
