# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameChatMessageTable extends _ModuleTable

var id: GameChatMessageIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "chat_message")
	set_meta("is_event", "false")
	set_meta("type", "GameChatMessage")

static func create(p_local_db: LocalDatabase) -> GameChatMessageTable:
	var table: GameChatMessageTable = GameChatMessageTable.new()
	table._db = p_local_db
	table.id = GameChatMessageIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameChatMessage]:
	var rows: Array = super()
	var typed_array: Array[GameChatMessage] = []
	typed_array.assign(rows)
	return typed_array
