# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameAccountStateTable extends _ModuleTable

var account: GameAccountStateAccountUniqueIndex

func _init() -> void:
	set_meta("table_name", "account_state")
	set_meta("is_event", "false")
	set_meta("type", "GameAccountState")

static func create(p_local_db: LocalDatabase) -> GameAccountStateTable:
	var table: GameAccountStateTable = GameAccountStateTable.new()
	table._db = p_local_db
	table.account = GameAccountStateAccountUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameAccountState]:
	var rows: Array = super()
	var typed_array: Array[GameAccountState] = []
	typed_array.assign(rows)
	return typed_array
