# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameItemDropTable extends _ModuleTable

var id: GameItemDropIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "item_drop")
	set_meta("is_event", "false")
	set_meta("type", "GameItemDrop")

static func create(p_local_db: LocalDatabase) -> GameItemDropTable:
	var table: GameItemDropTable = GameItemDropTable.new()
	table._db = p_local_db
	table.id = GameItemDropIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameItemDrop]:
	var rows: Array = super()
	var typed_array: Array[GameItemDrop] = []
	typed_array.assign(rows)
	return typed_array
