# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameCharacterSkillTable extends _ModuleTable

var id: GameCharacterSkillIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "character_skill")
	set_meta("is_event", "false")
	set_meta("type", "GameCharacterSkill")

static func create(p_local_db: LocalDatabase) -> GameCharacterSkillTable:
	var table: GameCharacterSkillTable = GameCharacterSkillTable.new()
	table._db = p_local_db
	table.id = GameCharacterSkillIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameCharacterSkill]:
	var rows: Array = super()
	var typed_array: Array[GameCharacterSkill] = []
	typed_array.assign(rows)
	return typed_array
