# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameMonsterIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, GameMonster] = {}

func _init() -> void:
	set_meta("table_name", "monster")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> GameMonsterIdUniqueIndex:
	var index: GameMonsterIdUniqueIndex = GameMonsterIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> GameMonster:
	return _cache.get(col_val, null)
