# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameSimulationClockIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, GameSimulationClock] = {}

func _init() -> void:
	set_meta("table_name", "simulation_clock")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> GameSimulationClockIdUniqueIndex:
	var index: GameSimulationClockIdUniqueIndex = GameSimulationClockIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> GameSimulationClock:
	return _cache.get(col_val, null)
