# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameNpcSpawnSpawnIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[String, GameNpcSpawn] = {}

func _init() -> void:
	set_meta("table_name", "npc_spawn")
	set_meta("field_name", "spawn_id")

static func create(p_local_db: LocalDatabase) -> GameNpcSpawnSpawnIdUniqueIndex:
	var index: GameNpcSpawnSpawnIdUniqueIndex = GameNpcSpawnSpawnIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: String) -> GameNpcSpawn:
	return _cache.get(col_val, null)
