# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameInventoryAccessCharacterIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, GameInventoryAccess] = {}

func _init() -> void:
	set_meta("table_name", "inventory_access")
	set_meta("field_name", "character_id")

static func create(p_local_db: LocalDatabase) -> GameInventoryAccessCharacterIdUniqueIndex:
	var index: GameInventoryAccessCharacterIdUniqueIndex = GameInventoryAccessCharacterIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: PackedByteArray) -> GameInventoryAccess:
	return _cache.get(col_val, null)
