# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameChargeStatusTable extends _ModuleTable

var character_id: GameChargeStatusCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "charge_status")
	set_meta("is_event", "false")
	set_meta("type", "GameChargeStatus")

static func create(p_local_db: LocalDatabase) -> GameChargeStatusTable:
	var table: GameChargeStatusTable = GameChargeStatusTable.new()
	table._db = p_local_db
	table.character_id = GameChargeStatusCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameChargeStatus]:
	var rows: Array = super()
	var typed_array: Array[GameChargeStatus] = []
	typed_array.assign(rows)
	return typed_array
