# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameMonsterStunTable extends _ModuleTable

var monster_id: GameMonsterStunMonsterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "monster_stun")
	set_meta("is_event", "false")
	set_meta("type", "GameMonsterStun")

static func create(p_local_db: LocalDatabase) -> GameMonsterStunTable:
	var table: GameMonsterStunTable = GameMonsterStunTable.new()
	table._db = p_local_db
	table.monster_id = GameMonsterStunMonsterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameMonsterStun]:
	var rows: Array = super()
	var typed_array: Array[GameMonsterStun] = []
	typed_array.assign(rows)
	return typed_array
