# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GamePlayerAppearanceTable extends _ModuleTable

var character_id: GamePlayerAppearanceCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "player_appearance")
	set_meta("is_event", "false")
	set_meta("type", "GamePlayerAppearance")

static func create(p_local_db: LocalDatabase) -> GamePlayerAppearanceTable:
	var table: GamePlayerAppearanceTable = GamePlayerAppearanceTable.new()
	table._db = p_local_db
	table.character_id = GamePlayerAppearanceCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GamePlayerAppearance]:
	var rows: Array = super()
	var typed_array: Array[GamePlayerAppearance] = []
	typed_array.assign(rows)
	return typed_array
