# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameNpcInteractionTable extends _ModuleTable

var session_id: GameNpcInteractionSessionIdUniqueIndex
var character_id: GameNpcInteractionCharacterIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "npc_interaction")
	set_meta("is_event", "false")
	set_meta("type", "GameNpcInteraction")

static func create(p_local_db: LocalDatabase) -> GameNpcInteractionTable:
	var table: GameNpcInteractionTable = GameNpcInteractionTable.new()
	table._db = p_local_db
	table.session_id = GameNpcInteractionSessionIdUniqueIndex.create(p_local_db)
	table.character_id = GameNpcInteractionCharacterIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameNpcInteraction]:
	var rows: Array = super()
	var typed_array: Array[GameNpcInteraction] = []
	typed_array.assign(rows)
	return typed_array
