# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameLootTable extends _ModuleTable

var id: GameLootIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "loot")
	set_meta("is_event", "false")
	set_meta("type", "GameLoot")

static func create(p_local_db: LocalDatabase) -> GameLootTable:
	var table: GameLootTable = GameLootTable.new()
	table._db = p_local_db
	table.id = GameLootIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameLoot]:
	var rows: Array = super()
	var typed_array: Array[GameLoot] = []
	typed_array.assign(rows)
	return typed_array
