# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameCommandFeedbackTable extends _ModuleTable

var id: GameCommandFeedbackIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "command_feedback")
	set_meta("is_event", "false")
	set_meta("type", "GameCommandFeedback")

static func create(p_local_db: LocalDatabase) -> GameCommandFeedbackTable:
	var table: GameCommandFeedbackTable = GameCommandFeedbackTable.new()
	table._db = p_local_db
	table.id = GameCommandFeedbackIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameCommandFeedback]:
	var rows: Array = super()
	var typed_array: Array[GameCommandFeedback] = []
	typed_array.assign(rows)
	return typed_array
