# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name GameObstacleTable extends _ModuleTable

var id: GameObstacleIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "obstacle")
	set_meta("is_event", "false")
	set_meta("type", "GameObstacle")

static func create(p_local_db: LocalDatabase) -> GameObstacleTable:
	var table: GameObstacleTable = GameObstacleTable.new()
	table._db = p_local_db
	table.id = GameObstacleIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[GameObstacle]:
	var rows: Array = super()
	var typed_array: Array[GameObstacle] = []
	typed_array.assign(rows)
	return typed_array
